#!/usr/bin/env bash
# Shared DwarFS engine. Source from a launcher or run an explicit action.
if [[ -z ${BASH_VERSION:-} ]] || shopt -qo posix; then
    printf '%s\n' 'Bash is required.' >&2
    exit 1
fi
ACTIONS_PATH=$(readlink -f -- "${BASH_SOURCE[0]}")
ACTIONS_DIR=${ACTIONS_PATH%/*}
GAME_DIR=${GAME_DIR:-$ACTIONS_DIR}
GAME_DIR=$(realpath -e -- "$GAME_DIR") || {
    if [[ ${BASH_SOURCE[0]} == "$0" ]]; then exit 1; else return 1; fi
}

# Read configuration before resolving paths and compression options. No files are
# generated by help, compression, or sourcing this engine.
for config in "$HOME/.jc141rc" "$GAME_DIR/local.config" "$GAME_DIR/language.config"; do
    if [[ -f $config ]]; then
        # shellcheck disable=SC1090
        source "$config" || {
            if [[ ${BASH_SOURCE[0]} == "$0" ]]; then exit 1; else return 1; fi
        }
    fi
done
# Configured paths stay relative to the game directory when a launcher invokes
# this engine again from inside game-root. Explicit compression args use cwd.
game_path() {
    local path=$1
    [[ $path == /* ]] || path=$GAME_DIR/$path
    realpath -m -- "$path"
}
GAME_ROOT=$(game_path "${GAME_ROOT:-files/game-root}")
DWARFS_IMAGE=$(game_path "${DWARFS_IMAGE:-files/game-root.dwarfs}")
DWARFS_TREE=$(game_path "${DWARFS_TREE:-files/dwarfs-tree}")
JC_DIRECTORY=$(game_path "${JC_DIRECTORY:-$HOME/Games/jc141}")
if [[ -n ${DWARFS_PROFILES_DIR:-} ]]; then
    DWARFS_PROFILES_DIR=$(game_path "$DWARFS_PROFILES_DIR")
fi

log_info() { printf '[INFO] %s\n' "$*"; }
log_error() { printf '[ERROR] %s\n' "$*" >&2; }

# Serialize transitions on the existing game directory, without creating a lock
# file. A launcher keeps this lock for its session; daemons never inherit fd 9.
mount_lock() {
    [[ ${MOUNT_LOCK_HELD:-0} != 1 ]] || return 0
    exec 9<"$GAME_DIR" || return 1
    flock "${1:---exclusive}" 9 || { log_error "Another operation is using $GAME_DIR"; return 1; }
    MOUNT_LOCK_HELD=1
}

# Run CLI operations and launches in their own process group. Killing just the
# wrapper must also stop workers before they can publish an interrupted result.
run_managed() {
    local child status
    set -m
    (
        trap - EXIT
        # Keep the group leader alive until foreground workers have finished
        # their EXIT cleanup; the parent waits for this leader before returning.
        trap 'exit 130' INT
        trap 'exit 143' TERM
        trap 'exit 129' HUP
        "$@"
    ) 9<&- &
    child=$!
    trap 'stop_managed INT 130' INT
    trap 'stop_managed TERM 143' TERM
    trap 'stop_managed HUP 129' HUP
    wait "$child"
    status=$?
    trap - INT TERM HUP
    return "$status"
}
stop_managed() {
    trap '' INT TERM HUP
    kill -s "$1" -- "-$child" 2>/dev/null || true
    wait "$child" 2>/dev/null || true
    exit "$2"
}

# Resolve only the tool needed by an action. System packages contain separate
# binaries; game bundles may contain a universal binary or just the FUSE driver.
dwarfs_tool() {
    local tool=$1 bundle=$GAME_DIR/files/dwarfs-binary output
    shift
    if [[ -x $bundle && -z ${BUNDLE_KIND:-} ]]; then
        # FUSE accepts --help even alongside unknown options; success alone is
        # insufficient. A universal probe must actually produce mkdwarfs help.
        if output=$("$bundle" --tool=mkdwarfs --help 2>&1) && [[ $output == *--compress-level* ]]; then
            BUNDLE_KIND=universal
        elif output=$("$bundle" --help 2>&1) && [[ $output == *--compress-level* ]]; then
            BUNDLE_KIND=mkdwarfs
        else
            BUNDLE_KIND=dwarfs
        fi
    fi
    case ${BUNDLE_KIND:-system}:$tool in
        universal:*) "$bundle" --tool="$tool" "$@";;
        mkdwarfs:mkdwarfs|dwarfs:dwarfs) "$bundle" "$@";;
        *) "$tool" "$@";;
    esac
}

# Strings accept shell quoting without expansion; arrays in local.config avoid
# parsing entirely. Python's shlex and tomllib are part of the ISO baseline.
parse_words() {
    local result
    WORDS=()
    [[ -n $1 ]] || return 0
    result=$(python3 - "$1" <<'PYTHON'
import shlex, sys
try:
    words = shlex.split(sys.argv[1])
    if any("\n" in word or "\0" in word for word in words):
        raise ValueError("use a Bash array for arguments containing newlines")
    print("\n".join(words + ["END"]), end="")
except ValueError as exc:
    sys.exit(str(exc))
PYTHON
    ) || return 1
    mapfile -t WORDS <<< "$result"
    unset 'WORDS[-1]'
}

compression_options() {
    local profile=${DWARFS_PROFILE:-balanced} file result
    file=${DWARFS_PROFILES_DIR:-$ACTIONS_DIR/../03_tools/profiles}/$profile.toml
    [[ -f $file ]] || file=$GAME_DIR/$profile.toml
    [[ -f $file ]] || { log_error "Missing profile $profile; set DWARFS_PROFILES_DIR or copy $profile.toml beside actions.sh."; return 1; }
    result=$(python3 - "$file" "${DWARFS_LEVEL:-}" "${DWARFS_REPRODUCIBLE:-0}" <<'PYTHON'
import sys, tomllib
try:
    with open(sys.argv[1], "rb") as stream:
        data = tomllib.load(stream)
    data.setdefault("no_history", True)
    if sys.argv[2]:
        data["level"] = int(sys.argv[2])
    if sys.argv[3] == "1":
        data.update(set_time=0, no_create_timestamp=True, no_history=True,
                    num_workers=1, num_segmenter_workers=1)
    mapping = {"level": "compress-level", "block_size_bits": "block-size-bits",
               "max_lookback": "max-lookback-blocks", "order": "order",
               "compression": "compression", "categorize": "categorize",
               "set_time": "set-time", "num_workers": "num-workers",
               "num_segmenter_workers": "num-segmenter-workers"}
    flags = {"no_create_timestamp": "no-create-timestamp", "no_history": "no-history"}
    unknown = data.keys() - mapping.keys() - flags.keys() - {"note", "input", "output", "incompressible_compression"}
    if unknown:
        raise ValueError(f"unknown compression keys: {', '.join(sorted(unknown))}")
    ints = {"level": (0, 9), "block_size_bits": (10, 30), "max_lookback": (0, None), "num_workers": (1, None), "num_segmenter_workers": (1, None)}
    for key, flag in mapping.items():
        if key not in data:
            continue
        value = data[key]
        if key in ints:
            lo, hi = ints[key]
            if type(value) is not int or value < lo or (hi is not None and value > hi):
                raise ValueError(f"invalid {key}: {value!r}")
        elif not isinstance(value, str) and not (key == "set_time" and type(value) is int):
            raise ValueError(f"invalid {key}: {value!r}")
        if any(char in str(value) for char in "\n\0"):
            raise ValueError(f"invalid control character in {key}")
        print(f"--{flag}={value}")
    for key, flag in flags.items():
        if key in data and type(data[key]) is not bool:
            raise ValueError(f"{key} must be boolean")
        if data.get(key):
            print(f"--{flag}")
    cats = data.get("categorize", "").split(",")
    if "pcmaudio" in cats:
        print("--compression=pcmaudio/waveform::flac")
    if "incompressible" in cats:
        value = data.get("incompressible_compression", "null")
        if not isinstance(value, str) or any(char in value for char in "\n\0"):
            raise ValueError("invalid incompressible_compression")
        print(f"--compression=incompressible::{value}")
except (OSError, ValueError) as exc:
    sys.exit(str(exc))
PYTHON
    ) || return 1
    MK_OPTS=()
    [[ -z $result ]] || mapfile -t MK_OPTS <<< "$result"
    MK_OPTS+=("--set-owner=${DWARFS_OWNER:-$EUID}" "--set-group=${DWARFS_GROUP:-$(id -g)}")
    [[ -z ${DWARFS_FILTER:-} ]] || MK_OPTS+=(--filter "$DWARFS_FILTER")
}

# Scan once, with no filename splitting or du batching errors.
auto_categories() {
    local result opt categories=
    local -a remaining=()
    for opt in "${MK_OPTS[@]}"; do
        if [[ $opt == --categorize=* ]]; then categories=${opt#--categorize=}; else remaining+=("$opt"); fi
    done
    result=$(python3 - "$1" "$categories" <<'PYTHON'
import os, sys
wav = size = 0
def fail(exc):
    raise exc
try:
    for root, _, files in os.walk(sys.argv[1], onerror=fail):
        for name in files:
            path = os.path.join(root, name)
            if os.path.islink(path):
                continue
            ext = os.path.splitext(name)[1].lower()
            if ext == ".wav":
                wav += 1
            elif ext in {".pak", ".zip", ".mp4", ".bin"}:
                size += os.stat(path).st_size
    cats = list(dict.fromkeys(filter(None, sys.argv[2].split(",") +
        (["pcmaudio"] if wav > 5 else []) + (["incompressible"] if size > 500 * 1024**2 else []))))
    if "incompressible" in cats:
        cats.remove("incompressible")
        cats.append("incompressible")
    if cats:
        print("--categorize=" + ",".join(cats))
    if "pcmaudio" in cats and "pcmaudio" not in sys.argv[2].split(","):
        print("--compression=pcmaudio/waveform::flac")
    if "incompressible" in cats and "incompressible" not in sys.argv[2].split(","):
        print("--compression=incompressible::null")
except OSError as exc:
    sys.exit(str(exc))
PYTHON
    ) || return 1
    MK_OPTS=("${remaining[@]}")
    if [[ -n $result ]]; then
        local -a opts
        mapfile -t opts <<< "$result"
        MK_OPTS+=("${opts[@]}")
    fi
}

# A sibling temporary directory keeps partial images out of the final path.
# Linking publishes without overwriting an image created concurrently.
compress_one() (
    local src=$1 dst=$2 tmp
    [[ -d $src ]] || { log_error "Missing source directory: $src"; exit 1; }
    [[ ! -e $dst && ! -L $dst ]] || { log_error "Output exists: $dst"; exit 1; }
    if [[ $src == / || $dst == "$src" || $dst == "$src/"* ]]; then
        log_error 'Output must be outside the source directory.'; exit 1
    fi
    mkdir -p -- "$(dirname -- "$dst")" || exit 1
    tmp=$(mktemp -d -- "$dst.build.XXXXXXXX") || exit 1
    trap 'rm -rf -- "$tmp"' EXIT
    trap 'exit 130' INT
    trap 'exit 143' TERM HUP
    [[ ${DWARFS_AUTOCATEGORIZE:-0} != 1 ]] || auto_categories "$src" || exit 1
    log_info "Compressing $src -> $dst (profile: ${DWARFS_PROFILE:-balanced})"
    dwarfs_tool mkdwarfs "${MK_OPTS[@]}" -i "$src" -o "$tmp/image" || exit 1
    ln -T -- "$tmp/image" "$dst" || exit 1
    if [[ ${DWARFS_PAR2:-0} == 1 ]]; then
        par2 create -n1 "$dst" || exit 1
    fi
    log_info "Created $dst"
)

dwarfs-compress() {
    (( $# <= 2 )) || { log_error 'Usage: dwarfs-compress [source [image]]'; return 1; }
    local src dst item
    src=$(realpath -e -- "${1:-$GAME_ROOT}") || return 1
    dst=$(realpath -m -- "${2:-$DWARFS_IMAGE}") || return 1
    compression_options || return 1
    if [[ ${DWARFS_PAR2:-0} == 1 ]] && ! command -v par2 &>/dev/null; then
        log_error 'DWARFS_PAR2=1 requires par2.'; return 1
    fi
    compress_one "$src" "$dst" || return 1
    if [[ $src == "$GAME_ROOT" && $dst == "$DWARFS_IMAGE" ]]; then
        if command -v tree &>/dev/null; then
            tree -a -s -- "$src" > "$DWARFS_TREE" || return 1
        else
            find "$src" -print > "$DWARFS_TREE" || return 1
        fi
        if (( $# == 0 )); then
            for item in "$GAME_DIR"/files/languages/*/; do
                [[ -d $item ]] || continue
                compress_one "${item%/}" "${item%/}.dwarfs" || return 1
            done
        fi
    fi
}

is_mounted() { findmnt --mountpoint "$1" --noheadings >/dev/null; }
nonempty() { [[ -n $(find "$1" -mindepth 1 -maxdepth 1 -printf x -quit) ]]; }
language_paths() {
    LANGUAGE_MOUNT=
    if [[ -n ${_LANGUAGE:-} ]]; then
        [[ $_LANGUAGE != */* && $_LANGUAGE != . && $_LANGUAGE != .. ]] || { log_error 'Invalid language name.'; return 1; }
        LANGUAGE_MOUNT=$GAME_DIR/files/languages/.$_LANGUAGE-mnt
    fi
}

_dwarfs_unmount() {
    language_paths || return 1
    local dir
    for dir in "$GAME_ROOT" "$LANGUAGE_MOUNT" "$GAME_DIR/files/.game-root-mnt"; do
        [[ -n $dir ]] || continue
        if is_mounted "$dir"; then
            fusermount3 -u -- "$dir" || { log_error "Cannot unmount $dir; backing directories retained."; return 1; }
        fi
    done
    # Never recursively remove a mountpoint or overlay work directory.
    for dir in "$GAME_ROOT" "$LANGUAGE_MOUNT" "$GAME_DIR/files/.game-root-mnt"; do
        [[ -z $dir || ! -d $dir ]] || rmdir -- "$dir" 2>/dev/null || true
    done
    log_info 'Unmounted; overlay-storage retained.'
}

dwarfs-unmount() (
    trap - EXIT
    mount_lock || exit 1
    _dwarfs_unmount
)
dwarfs-mount() (
    trap - EXIT
    mount_lock || exit 1
    trap 'exit 130' INT
    trap 'exit 143' TERM
    trap 'exit 129' HUP
    _dwarfs_mount
)
_dwarfs_mount() {
    language_paths || return 1
    if is_mounted "$GAME_ROOT"; then
        log_info "Already mounted: $GAME_ROOT"; return 0
    fi
    if [[ -d $GAME_ROOT ]] && nonempty "$GAME_ROOT"; then
        log_info "Using extracted files: $GAME_ROOT"; return 0
    fi
    [[ -f $DWARFS_IMAGE ]] || { log_error "Missing image: $DWARFS_IMAGE"; return 1; }
    local lower=$GAME_DIR/files/.game-root-mnt mem key value rest
    local -a opts=(-o tidy_strategy=time -o tidy_interval=15m -o tidy_max_age=30m -o clone_fd)
    for key in "$GAME_ROOT" "$lower" "$GAME_DIR/files/overlay-storage" "$GAME_DIR/files/.game-root-work" "$LANGUAGE_MOUNT"; do
        [[ $key != *[:,\\]* ]] || { log_error 'Overlay paths cannot contain commas, colons, or backslashes.'; return 1; }
    done
    while read -r key value rest; do
        if [[ $key == MemTotal: ]]; then mem=$value; break; fi
    done < /proc/meminfo
    opts+=(-o "cachesize=$((mem / 4))k")
    if [[ -n ${DWARFS_ANALYSIS_FILE:-} ]]; then opts+=(-o "analysis_file=$DWARFS_ANALYSIS_FILE"); fi
    parse_words "${DWARFS_EXTRA_OPTS:-}" || return 1
    opts+=("${WORDS[@]}")
    _dwarfs_unmount || return 1
    trap '_dwarfs_unmount >&2' EXIT
    mkdir -p -- "$lower" "$GAME_DIR/files/overlay-storage" "$GAME_DIR/files/.game-root-work" "$GAME_ROOT" || return 1
    dwarfs_tool dwarfs "$DWARFS_IMAGE" "$lower" "${opts[@]}" 9<&- || return 1
    if [[ -n $LANGUAGE_MOUNT ]]; then
        mkdir -p -- "$LANGUAGE_MOUNT" || return 1
        dwarfs_tool dwarfs "$GAME_DIR/files/languages/$_LANGUAGE.dwarfs" "$LANGUAGE_MOUNT" "${opts[@]}" 9<&- || return 1
        lower=$LANGUAGE_MOUNT:$lower
    fi
    fuse-overlayfs -o "squash_to_uid=$EUID,squash_to_gid=$(id -g),lowerdir=$lower,upperdir=$GAME_DIR/files/overlay-storage,workdir=$GAME_DIR/files/.game-root-work" "$GAME_ROOT" 9<&- || return 1
    is_mounted "$GAME_ROOT" || { log_error 'Overlay mount did not become ready.'; return 1; }
    trap - EXIT
    log_info 'Mounted; overlay-storage persists writes.'
}

dwarfs-unmount-gamescope() {
    if [[ -n ${WINEPREFIX:-} ]]; then
        WINEPREFIX=$(game_path "$WINEPREFIX") wineserver -k || return 1
    fi
    dwarfs-unmount
}

extract_one() (
    local image=$1 target=$2 tmp
    mount_lock || exit 1
    if is_mounted "$target"; then log_error "Unmount before extracting: $target"; exit 1; fi
    if [[ -d $target ]] && nonempty "$target"; then log_info "Already extracted: $target"; exit 0; fi
    [[ -f $image ]] || { log_error "Missing image: $image"; exit 1; }
    mkdir -p -- "$(dirname -- "$target")" || exit 1
    tmp=$(mktemp -d -- "$target.extract.XXXXXXXX") || exit 1
    trap 'rm -rf -- "$tmp"' EXIT
    trap 'exit 130' INT
    trap 'exit 143' TERM HUP
    parse_words "${DWARFSEXTRACT_EXTRA:-}" || exit 1
    dwarfs_tool dwarfsextract --stdout-progress -i "$image" -o "$tmp" "${WORDS[@]}" || exit 1
    [[ ! -d $target ]] || rmdir -- "$target" || exit 1
    mv --no-copy -T -- "$tmp" "$target" || exit 1
)
dwarfs-extract() { extract_one "$DWARFS_IMAGE" "$GAME_ROOT"; }
dwarfs-extract-language() {
    language_paths || return 1
    [[ -n $LANGUAGE_MOUNT ]] || { log_error 'Set _LANGUAGE first.'; return 1; }
    extract_one "$GAME_DIR/files/languages/$_LANGUAGE.dwarfs" "$GAME_DIR/files/languages/$_LANGUAGE"
}
dwarfs-verify() {
    dwarfs_tool dwarfsck -i "$DWARFS_IMAGE" --check-integrity --detail=2 || return 1
    if [[ ${DWARFS_VERIFY_CHECKSUM:-0} == 1 ]]; then
        # These are image-content checksums, not a host-side checksum manifest.
        dwarfs_tool dwarfsck -i "$DWARFS_IMAGE" --checksum=sha256 || return 1
    fi
}
dwarfs-recompress() (
    local level=${1:-7} tmp
    [[ $level =~ ^[0-9]$ && $# -le 1 ]] || { log_error 'Level must be 0–9.'; exit 1; }
    [[ -f $DWARFS_IMAGE ]] || { log_error "Missing image: $DWARFS_IMAGE"; exit 1; }
    tmp=$(mktemp -d -- "$DWARFS_IMAGE.recompress.XXXXXXXX") || exit 1
    trap 'rm -rf -- "$tmp"' EXIT
    trap 'exit 130' INT
    trap 'exit 143' TERM HUP
    dwarfs_tool mkdwarfs --recompress -i "$DWARFS_IMAGE" -o "$tmp/image" -l "$level" || exit 1
    dwarfs_tool dwarfsck -i "$tmp/image" --check-integrity --quiet || exit 1
    mv --no-copy -T -- "$tmp/image" "$DWARFS_IMAGE" || exit 1
    log_info "Recompressed to level $level"
)
dwarfs-info() { dwarfs_tool dwarfsck -i "$DWARFS_IMAGE" --detail=2 --json; }

bwrap-run_in_sandbox() {
    local -a flags=(--unshare-pid --ro-bind / / --dev-bind /dev /dev --bind /tmp /tmp --proc /proc --die-with-parent)
    [[ ${BLOCK_NET:-1} != 1 ]] || flags+=(--unshare-net)
    if [[ ${ISOLATION_TYPE:-native} == wine ]]; then
        mkdir -p -- "$WINEPREFIX" || return 1
        flags+=(--bind "$WINEPREFIX" "$WINEPREFIX")
    else
        mkdir -p -- "$JC_DIRECTORY/native-docs" || return 1
        flags+=(--bind "$JC_DIRECTORY/native-docs" "$HOME")
    fi
    flags+=(--bind "$GAME_DIR" "$GAME_DIR" --bind "$GAME_ROOT" "$GAME_ROOT" --chdir "$GAME_ROOT")
    # Existing Wayland/audio runtime sockets remain visible through the root bind.
    bwrap "${flags[@]}" "$@"
}
gamescope-run_embedded() {
    local -a args=()
    [[ ${GAMESCOPE_FULLSCREEN:-1} != 1 ]] || args+=(-f)
    [[ ${GAMESCOPE_BORDERLESS:-0} != 1 ]] || args+=(-b)
    [[ -z ${GAMESCOPE_SCREEN_WIDTH:-} ]] || args+=(-W "$GAMESCOPE_SCREEN_WIDTH")
    [[ -z ${GAMESCOPE_SCREEN_HEIGHT:-} ]] || args+=(-H "$GAMESCOPE_SCREEN_HEIGHT")
    [[ -z ${GAMESCOPE_GAME_WIDTH:-} ]] || args+=(-w "$GAMESCOPE_GAME_WIDTH")
    [[ -z ${GAMESCOPE_GAME_HEIGHT:-} ]] || args+=(-h "$GAMESCOPE_GAME_HEIGHT")
    parse_words "${ADDITIONAL_FLAGS:-}" || return 1
    args+=("${WORDS[@]}")
    gamescope "${args[@]}" -- "$@"
}
help() {
    cat <<'EOF'
Usage: actions.sh ACTION [arguments]
  dwarfs-compress [source [image]]  Compress a directory (default: files/game-root)
  dwarfs-mount                      Mount a writable overlay
  dwarfs-unmount                    Unmount without deleting saved writes
  dwarfs-unmount-gamescope          Stop the selected Wine prefix, then unmount
  dwarfs-extract                    Extract atomically into files/game-root
  dwarfs-extract-language           Extract the selected _LANGUAGE
  dwarfs-verify                     Verify all image blocks
  dwarfs-recompress [0–9]           Recompress, verify, then replace the image
  dwarfs-info                       Show image metadata as JSON
  help
Profiles: DWARFS_PROFILE=balanced (or fast/max/game/game_ue/audio/reproducible).
Copied engines need DWARFS_PROFILES_DIR or a profile TOML beside actions.sh.
Configured paths are relative to GAME_DIR; source/image arguments use caller cwd.
Configuration: ~/.jc141rc, GAME_DIR/local.config, GAME_DIR/language.config.
EOF
}

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
    action=${1:-help}
    (( $# == 0 )) || shift
    case $action in
        dwarfs-mount|dwarfs-unmount|dwarfs-unmount-gamescope|dwarfs-extract|dwarfs-extract-language|dwarfs-compress|dwarfs-verify|dwarfs-recompress|dwarfs-info|bwrap-run_in_sandbox|help)
            run_managed "$action" "$@";;
        *) log_error "Unknown action: $action"; help; exit 1;;
    esac
fi
