# Dusky System Notification Ignore Configuration
# App names listed here will be hidden from both Dusky Quick Panel and Rofi Notification Menu.
# Wildcard suffix supported (e.g. "dusky-glance*")

[ignored]
apps = [
  "OSD",
  "dusky-recorder",
  "dusky-keys",
  "dusky-cava",
  "dusky-cava-alert",
  "dusky-glance*",
  "dusky-tlp",
  "dusky-high-ram-alert",
  "Spotify",
  "matugen-theme",
  "dusky-fav-wal",
]
