#!/usr/bin/env bash
# =============================================================================
#  kokoro_installer.sh - Dusky Kokoro TTS installer
#  Target: Arch Linux (rolling), CPython 3.14 managed by uv, systemd user session
#
#  What it does
#    1. scans GPUs through sysfs (vendor/class ids) and lspci, checks drivers
#    2. writes a per-hardware pyproject.toml and builds a locked, isolated venv
#       (uv lock + uv sync) in DUSKY_HOME - no --force-reinstall hacks:
#         * kokoro-onnx metadata is overridden with [[tool.uv.dependency-metadata]]
#           (drops its unconditional CPU "onnxruntime" pin, lifts its <3.14 cap)
#         * exactly ONE onnxruntime distribution ends up installed
#    3. downloads the Kokoro v1.0 ONNX models + voices with resume, retry,
#       exact-size and file-magic verification
#    4. writes config.toml (generated by the daemon itself), the systemd
#       socket + service units, and installs trigger.sh
#    5. runs an end-to-end self test (providers, model load, synthesis, RTF)
#
#  Usage: kokoro_installer.sh [--hw nvidia|amd|intel|cpu] [--models LIST|all]
#         [--rocm-source amd|arch] [--rocm-release 6.4] [--hsa-override 10.3.0]
#         [--home DIR] [--trigger-dir DIR] [--install-system-deps] [--no-systemd]
#         [--skip-models] [--skip-selftest] [--yes] [--uninstall] [--help]
#
#  Style note: no brace parameter expansions are used on purpose (see trigger.sh).
# =============================================================================
set -Eeuo pipefail
shopt -s inherit_errexit

INSTALLER_VERSION="5.0.0"
PY_SERIES="3.14"
KOKORO_ONNX_VERSION="0.6.1"     # pinned; its metadata is overridden below (see write_pyproject)
ORT_MIN="1.22"
OPENVINO_MIN="2025.1"
RELEASE_BASE="https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0"

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

DUSKY_HOME=$(printenv DUSKY_HOME || true)
[[ -n "$DUSKY_HOME" ]] || DUSKY_HOME="$HOME/contained_apps/uv/dusky_kokoro"
TRIGGER_DIR=$(printenv DUSKY_TRIGGER_DIR || true)
[[ -n "$TRIGGER_DIR" ]] || TRIGGER_DIR="$HOME/user_scripts/tts_stt/dusky_kokoro"
CONFIG_HOME=$(printenv XDG_CONFIG_HOME || true)
[[ -n "$CONFIG_HOME" ]] || CONFIG_HOME="$HOME/.config"

HW=""                 # nvidia | amd | intel | cpu
MODELS=""             # comma separated: fp16-gpu,f32,int8,fp16 | all
ROCM_SOURCE="amd"     # amd  = official wheels from repo.radeon.com (isolated venv)
                      # arch = python-onnxruntime-rocm from [extra] via --system-site-packages
ROCM_RELEASE=""       # e.g. 6.4 ; auto-detected from /opt/rocm/.info/version
HSA_OVERRIDE=""       # e.g. 10.3.0 ; auto-suggested from rocminfo for consumer parts
ASSUME_YES=0
NO_SYSTEMD=0
SKIP_MODELS=0
SKIP_SELFTEST=0
INSTALL_SYSTEM_DEPS=0
UNINSTALL=0

GPU_NVIDIA=0
GPU_AMD=0
GPU_INTEL=0

# --- output helpers -------------------------------------------------------------
if [[ -t 1 ]]; then
    C_INFO=$'\e[1;34m'; C_OK=$'\e[1;32m'; C_WARN=$'\e[1;33m'; C_ERR=$'\e[1;31m'; C_END=$'\e[0m'
else
    C_INFO=""; C_OK=""; C_WARN=""; C_ERR=""; C_END=""
fi
info() { printf '%s::%s %s\n' "$C_INFO" "$C_END" "$*"; }
ok()   { printf '%s [ok]%s %s\n' "$C_OK" "$C_END" "$*"; }
warn() { printf '%s [!!]%s %s\n' "$C_WARN" "$C_END" "$*" >&2; }
die()  { printf '%s [xx]%s %s\n' "$C_ERR" "$C_END" "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }
trap 'die "installer aborted (line $LINENO)"' ERR

show_help() {
    sed -n '2,25p' "$0" | sed 's/^#  \{0,1\}//'
}

# --- argument parsing -------------------------------------------------------------
while (( $# > 0 )); do
    case "$1" in
        -h|--help)             show_help; exit 0 ;;
        --hw)                  (( $# >= 2 )) || die "--hw needs an argument"; HW="$2"; shift ;;
        --models)              (( $# >= 2 )) || die "--models needs an argument"; MODELS="$2"; shift ;;
        --rocm-source)         (( $# >= 2 )) || die "--rocm-source needs an argument"; ROCM_SOURCE="$2"; shift ;;
        --rocm-release)        (( $# >= 2 )) || die "--rocm-release needs an argument"; ROCM_RELEASE="$2"; shift ;;
        --hsa-override)        (( $# >= 2 )) || die "--hsa-override needs an argument"; HSA_OVERRIDE="$2"; shift ;;
        --home)                (( $# >= 2 )) || die "--home needs an argument"; DUSKY_HOME="$2"; shift ;;
        --trigger-dir)         (( $# >= 2 )) || die "--trigger-dir needs an argument"; TRIGGER_DIR="$2"; shift ;;
        -y|--yes)              ASSUME_YES=1 ;;
        --no-systemd)          NO_SYSTEMD=1 ;;
        --skip-models)         SKIP_MODELS=1 ;;
        --skip-selftest)       SKIP_SELFTEST=1 ;;
        --install-system-deps) INSTALL_SYSTEM_DEPS=1 ;;
        --uninstall)           UNINSTALL=1 ;;
        *)                     die "unknown option: $1 (see --help)" ;;
    esac
    shift
done

case "$HW" in ""|nvidia|amd|intel|cpu) ;; *) die "--hw must be nvidia, amd, intel or cpu" ;; esac
case "$ROCM_SOURCE" in amd|arch) ;; *) die "--rocm-source must be amd or arch" ;; esac

CONFIG_DIR="$CONFIG_HOME/dusky-kokoro"
CONFIG_FILE="$CONFIG_DIR/config.toml"
UNIT_DIR="$CONFIG_HOME/systemd/user"
MODEL_DIR="$DUSKY_HOME/models"
VENV_PY="$DUSKY_HOME/.venv/bin/python"
MAIN_PY="$DUSKY_HOME/dusky_main.py"

# --- model manifest (exact byte sizes from the GitHub release API) ---------------------
model_file() {
    case "$1" in
        f32)      echo "kokoro-v1.0.onnx" ;;
        fp16)     echo "kokoro-v1.0.fp16.onnx" ;;
        fp16-gpu) echo "kokoro-v1.0.fp16-gpu.onnx" ;;
        int8)     echo "kokoro-v1.0.int8.onnx" ;;
        voices)   echo "voices-v1.0.bin" ;;
        *)        return 1 ;;
    esac
}
model_size() {
    case "$1" in
        f32)      echo 325532387 ;;
        fp16)     echo 177464787 ;;
        fp16-gpu) echo 177464787 ;;
        int8)     echo 92361271 ;;
        voices)   echo 0 ;;        # not pinned: verified by ZIP magic + minimum size
        *)        return 1 ;;
    esac
}

# --- uninstall -------------------------------------------------------------------------
if (( UNINSTALL )); then
    info "uninstalling Dusky Kokoro"
    if have systemctl; then
        systemctl --user disable --now dusky-kokoro.socket >/dev/null 2>&1 || true
        systemctl --user stop dusky-kokoro.service dusky-kokoro-adhoc.service >/dev/null 2>&1 || true
        rm -f "$UNIT_DIR/dusky-kokoro.socket" "$UNIT_DIR/dusky-kokoro.service"
        systemctl --user daemon-reload >/dev/null 2>&1 || true
    fi
    rm -f "$TRIGGER_DIR/trigger.sh" "$HOME/.local/bin/dusky-kokoro"
    if (( ASSUME_YES )) || { [[ -t 0 ]] && read -r -p "remove $DUSKY_HOME (venv + models)? [y/N] " a && [[ "$a" == y* ]]; }; then
        rm -rf "$DUSKY_HOME"
        ok "removed $DUSKY_HOME"
    fi
    info "kept $CONFIG_FILE and $HOME/.cache/dusky-kokoro (remove manually if desired)"
    exit 0
fi

# --- preflight --------------------------------------------------------------------------
preflight() {
    (( BASH_VERSINFO[0] >= 5 )) || die "bash 5+ is required"
    [[ -f /etc/arch-release ]] || warn "not an Arch Linux system - continuing, package hints will not apply"
    [[ -f "$SCRIPT_DIR/dusky_main.py" ]] || die "dusky_main.py must sit next to this installer ($SCRIPT_DIR)"
    [[ -f "$SCRIPT_DIR/trigger.sh" ]] || die "trigger.sh must sit next to this installer ($SCRIPT_DIR)"

    local missing=""
    have curl || missing="$missing curl"
    have mpv  || missing="$missing mpv"
    have notify-send || missing="$missing libnotify"
    if ! have wl-paste && ! have xclip && ! have xsel; then missing="$missing wl-clipboard"; fi
    if [[ -n "$missing" ]]; then
        if have pacman; then
            info "installing missing system packages via pacman:$missing"
            read -r -a _missing_arr <<< "$missing"
            sudo pacman -S --needed --noconfirm "${_missing_arr[@]}"
        else
            die "missing system packages:$missing  ->  please install them using your system package manager"
        fi
    fi
    if ! have uv; then
        if have pacman; then
            info "installing uv with sudo pacman"
            sudo pacman -S --needed --noconfirm uv || true
        fi
        if ! have uv; then
            info "installing uv with the official installer (~/.local/bin)"
            curl -LsSf https://astral.sh/uv/install.sh | sh
            export PATH="$HOME/.local/bin:$PATH"
        fi
        have uv || die "uv is still not on PATH"
    fi
    ok "uv $(uv --version | awk '{print $2}')"
}

# --- hardware scan ----------------------------------------------------------------------
scan_gpus() {
    local dev vendor class
    for dev in /sys/class/drm/card[0-9]*/device; do
        [[ -r "$dev/vendor" && -r "$dev/class" ]] || continue
        vendor=$(<"$dev/vendor")
        class=$(<"$dev/class")
        case "$class" in 0x0300*|0x0302*|0x0380*) ;; *) continue ;; esac
        case "$vendor" in
            0x10de) GPU_NVIDIA=1 ;;
            0x1002) GPU_AMD=1 ;;
            0x8086) GPU_INTEL=1 ;;
        esac
    done
    echo "--------------------------------------------------------------"
    info "GPU scan (sysfs class 0300/0302/0380):"
    if have lspci; then
        { lspci -d ::0300; lspci -d ::0302; lspci -d ::0380; } 2>/dev/null | sed 's/^/     /' || true
    fi
    (( GPU_NVIDIA )) && echo "     NVIDIA : yes  ($(head -n 1 /proc/driver/nvidia/version 2>/dev/null || echo 'kernel driver NOT loaded'))"
    (( GPU_AMD ))    && echo "     AMD    : yes  (ROCm: $(cat /opt/rocm/.info/version 2>/dev/null || echo 'not installed'))"
    (( GPU_INTEL ))  && echo "     Intel  : yes  ($(pacman -Q intel-compute-runtime 2>/dev/null || echo 'intel-compute-runtime not installed'))"
    if (( GPU_NVIDIA + GPU_AMD + GPU_INTEL == 0 )); then echo "     no discrete/integrated GPU with a display class found"; fi
    echo "--------------------------------------------------------------"
}

choose_hw() {
    local default="cpu"
    (( GPU_NVIDIA )) && default="nvidia"
    [[ "$default" == cpu ]] && (( GPU_AMD )) && default="amd"
    [[ "$default" == cpu ]] && (( GPU_INTEL )) && default="intel"
    if [[ -n "$HW" ]]; then info "hardware mode: $HW (from --hw)"; return 0; fi
    if (( ASSUME_YES )) || [[ ! -t 0 ]]; then HW="$default"; info "hardware mode: $HW (auto-detected)"; return 0; fi
    echo
    echo "Select the inference backend:"
    echo "  1) NVIDIA  CUDA      onnxruntime-gpu + NVIDIA runtime wheels (no system CUDA toolkit needed)"
    echo "  2) AMD     ROCm      official AMD wheels (or Arch python-onnxruntime-rocm with --rocm-source arch)"
    echo "  3) Intel   OpenVINO  onnxruntime-openvino: Intel GPU / NPU / CPU"
    echo "  4) CPU     only"
    local answer
    read -r -e -p "Choice [1-4] (detected default: $default): " answer || answer=""
    case "$answer" in
        1) HW=nvidia ;; 2) HW=amd ;; 3) HW=intel ;; 4) HW=cpu ;; "") HW="$default" ;;
        *) die "invalid choice" ;;
    esac
    info "hardware mode: $HW"
}

choose_models() {
    local default
    case "$HW" in nvidia|amd) default="fp16-gpu" ;; *) default="int8" ;; esac
    if [[ -n "$MODELS" ]]; then :;
    elif (( ASSUME_YES )) || [[ ! -t 0 ]]; then MODELS="$default"
    else
        echo
        echo "Select the model precision files to download:"
        echo "  1) fp16-gpu  177 MB  GPU-optimised half precision   (recommended for NVIDIA / ROCm: 12x real-time on Tensor Cores)"
        echo "  2) int8       92 MB  quantised compact              (recommended for CPU: 92 MB, fastest on CPU)"
        echo "  3) f32       326 MB  full precision float32"
        echo "  4) fp16      177 MB  generic half precision"
        echo "  5) all"
        local answer
        read -r -e -p "Choice [1-5] (default: $default): " answer || answer=""
        case "$answer" in
            1) MODELS=fp16-gpu ;; 2) MODELS=int8 ;; 3) MODELS=f32 ;; 4) MODELS=fp16 ;; 5) MODELS=all ;;
            "") MODELS="$default" ;; *) die "invalid choice" ;;
        esac
    fi
    [[ "$MODELS" == all ]] && MODELS="fp16-gpu,f32,int8,fp16"
    local m
    for m in $(tr ',' ' ' <<<"$MODELS"); do model_file "$m" >/dev/null || die "unknown model precision '$m'"; done
    info "models: $MODELS (+ voices)"
}

# --- per-hardware prerequisites ---------------------------------------------------------------
check_hw_prereqs() {
    case "$HW" in
        nvidia)
            [[ -r /proc/driver/nvidia/version ]] || die "NVIDIA kernel driver not loaded (sudo pacman -S nvidia-open nvidia-utils; reboot)"
            if have nvidia-smi; then
                info "nvidia-smi: $(nvidia-smi --query-gpu=name,driver_version,memory.total --format=csv,noheader 2>/dev/null | head -n 1)"
            fi
            ;;
        amd)
            if [[ "$ROCM_SOURCE" == amd ]]; then
                [[ -d /opt/rocm ]] || die "ROCm runtime not found in /opt/rocm (sudo pacman -S rocm-hip-runtime miopen-hip rocblas hipblas hipfft rccl)"
                if [[ -z "$ROCM_RELEASE" ]]; then
                    ROCM_RELEASE=$(cut -d. -f1,2 /opt/rocm/.info/version 2>/dev/null | tr -dc '0-9.' || true)
                fi
                [[ -n "$ROCM_RELEASE" ]] || die "cannot detect the ROCm release; pass --rocm-release X.Y"
                info "ROCm release: $ROCM_RELEASE  (wheel index: repo.radeon.com/rocm/manylinux/rocm-rel-$ROCM_RELEASE/)"
            else
                pacman -Q python-onnxruntime-rocm >/dev/null 2>&1 || pacman -Q python-onnxruntime-opt-rocm >/dev/null 2>&1 \
                    || die "install the Arch package first: sudo pacman -S python-onnxruntime-rocm"
                local sys_py
                sys_py=$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])' 2>/dev/null || echo "none")
                [[ "$sys_py" == "$PY_SERIES" ]] || die "--rocm-source arch needs the system python ($sys_py) to be $PY_SERIES so its compiled modules import in the venv"
            fi
            [[ -e /dev/kfd ]] || warn "/dev/kfd missing - amdgpu KFD not available, ROCm will not work"
            id -nG | grep -qw render || warn "user is not in the 'render' group (sudo usermod -aG render,video $USER; re-login)"
            detect_hsa_override
            ;;
        intel)
            ls /dev/dri/renderD* >/dev/null 2>&1 || warn "no /dev/dri/renderD* node - OpenVINO GPU device unavailable (CPU device still works)"
            pacman -Q intel-compute-runtime >/dev/null 2>&1 || warn "intel-compute-runtime not installed: OpenVINO GPU plugin needs it (sudo pacman -S intel-compute-runtime)"
            ;;
        cpu) ;;
    esac
}

detect_hsa_override() {
    [[ -z "$HSA_OVERRIDE" ]] || return 0
    have rocminfo || return 0
    local gfx
    gfx=$(rocminfo 2>/dev/null | grep -m1 -oE 'gfx[0-9a-f]+' || true)
    case "$gfx" in
        gfx1031|gfx1032|gfx1033|gfx1034|gfx1035|gfx1036) HSA_OVERRIDE="10.3.0" ;;
        gfx1010|gfx1011|gfx1012)                          HSA_OVERRIDE="10.3.0" ;;
        gfx1101|gfx1102|gfx1103)                          HSA_OVERRIDE="11.0.0" ;;
        *) ;;
    esac
    if [[ -n "$HSA_OVERRIDE" ]]; then
        warn "ROCm: $gfx has no native MIOpen/rocBLAS kernels -> HSA_OVERRIDE_GFX_VERSION=$HSA_OVERRIDE will be set in config.toml"
    elif [[ -n "$gfx" ]]; then
        info "ROCm target: $gfx"
    fi
}

# --- python environment -----------------------------------------------------------------------
write_pyproject() {
    local ort_line="" index_block=""
    case "$HW" in
        nvidia) ort_line="    \"onnxruntime-gpu[cuda,cudnn]>=$ORT_MIN\"," ;;
        amd)    if [[ "$ROCM_SOURCE" == amd ]]; then ort_line="    \"onnxruntime-rocm>=$ORT_MIN\","; fi ;;
        intel)  ort_line="    \"onnxruntime-openvino>=$ORT_MIN\","$'\n'"    \"openvino>=$OPENVINO_MIN\"," ;;
        cpu)    ort_line="    \"onnxruntime>=$ORT_MIN\"," ;;
    esac
    if [[ "$HW" == amd && "$ROCM_SOURCE" == amd ]]; then
        index_block=$(cat <<EOF

# AMD publishes ROCm builds of onnxruntime as a flat (find-links style) index per ROCm release.
[[tool.uv.index]]
name = "amd-rocm"
url = "https://repo.radeon.com/rocm/manylinux/rocm-rel-$ROCM_RELEASE/"
format = "flat"
explicit = true

[tool.uv.sources]
onnxruntime-rocm = { index = "amd-rocm" }
EOF
)
    fi
    cat > "$DUSKY_HOME/pyproject.toml" <<EOF
# Generated by kokoro_installer.sh $INSTALLER_VERSION - hardware mode: $HW
# Re-run the installer to switch hardware modes; "uv sync" reconciles the environment.
[project]
name = "dusky-kokoro"
version = "$INSTALLER_VERSION"
description = "Dusky Kokoro TTS daemon environment ($HW)"
requires-python = ">=$PY_SERIES"
dependencies = [
    "kokoro-onnx==$KOKORO_ONNX_VERSION",
    "numpy>=2.3",
$ort_line
]

[tool.uv]
package = false
$index_block

# kokoro-onnx $KOKORO_ONNX_VERSION declares requires-python "<3.14" (its own CI cap, the code is pure
# Python) and an UNCONDITIONAL dependency on the CPU "onnxruntime" wheel. Installing that next to
# onnxruntime-gpu / -rocm / -openvino makes two distributions write the same "onnxruntime/"
# package directory - the root cause of the old --force-reinstall hack. uv lets us replace the
# declared metadata of exactly this package, so precisely one onnxruntime distribution is resolved.
[[tool.uv.dependency-metadata]]
name = "kokoro-onnx"
version = "$KOKORO_ONNX_VERSION"
requires-python = ">=3.10"
requires-dist = [
    "espeakng-loader>=0.2.4",
    "phonemizer>=3.4.0",
    "numpy>=2.0.2",
]
EOF
    ok "wrote $DUSKY_HOME/pyproject.toml"
}

setup_env() {
    mkdir -p "$DUSKY_HOME" "$MODEL_DIR"
    if [[ "$SCRIPT_DIR/dusky_main.py" -ef "$MAIN_PY" ]]; then
        ok "dusky_main.py already in place"
    else
        install -m 644 "$SCRIPT_DIR/dusky_main.py" "$MAIN_PY"
        ok "deployed dusky_main.py"
    fi
    write_pyproject
    cd "$DUSKY_HOME"
    if ! uv python find "$PY_SERIES" >/dev/null 2>&1; then
        info "ensuring CPython $PY_SERIES (uv-managed)"
        uv python install "$PY_SERIES"
    else
        info "using CPython $PY_SERIES: $(uv python find "$PY_SERIES")"
    fi
    printf '%s\n' "$PY_SERIES" > .python-version
    if [[ "$HW" == amd && "$ROCM_SOURCE" == arch ]]; then
        uv venv --clear --python "$PY_SERIES" --system-site-packages
    else
        uv venv --clear --python "$PY_SERIES"
    fi
    info "resolving (uv lock) and syncing the environment"
    uv lock
    uv sync --locked
    ok "environment ready: $VENV_PY ($("$VENV_PY" --version))"
}

verify_runtime() {
    local expected providers count
    case "$HW" in
        nvidia) expected="CUDAExecutionProvider" ;;
        amd)    expected="ROCmExecutionProvider" ;;
        intel)  expected="OpenVINOExecutionProvider" ;;
        cpu)    expected="CPUExecutionProvider" ;;
    esac
    cd "$DUSKY_HOME"
    count=$(uv pip list 2>/dev/null | grep -ciE '^onnxruntime' || true)
    if [[ "$HW" == amd && "$ROCM_SOURCE" == arch ]]; then
        (( count == 0 )) || warn "an onnxruntime wheel is installed in the venv although --rocm-source arch was requested"
    else
        (( count == 1 )) || warn "expected exactly one onnxruntime distribution in the venv, found $count"
    fi
    providers=$("$VENV_PY" -c 'import onnxruntime as o; hasattr(o, "preload_dlls") and o.preload_dlls(); print(" ".join(o.get_available_providers()))')
    info "onnxruntime providers: $providers"
    if grep -qw "$expected" <<<"$providers"; then
        ok "$expected is available"
    else
        warn "$expected is NOT part of this onnxruntime build - the daemon would run on the CPU"
    fi
}

# --- models -------------------------------------------------------------------------------------
download() {  # key
    local key="$1" name size url dest tmp actual magic
    name=$(model_file "$key")
    size=$(model_size "$key")
    url="$RELEASE_BASE/$name"
    dest="$MODEL_DIR/$name"
    tmp="$dest.part"
    if [[ -f "$dest" ]]; then
        actual=$(stat -c %s "$dest")
        if [[ "$size" == 0 && "$actual" -gt 1000000 ]] || [[ "$actual" == "$size" ]]; then
            ok "present: $name ($actual bytes)"
            return 0
        fi
        warn "$name has $actual bytes (expected $size) - downloading again"
        rm -f "$dest"
    fi
    info "downloading $name"
    curl --fail --location --retry 5 --retry-all-errors --retry-delay 2 --continue-at - \
         --progress-bar --output "$tmp" "$url"
    actual=$(stat -c %s "$tmp")
    if [[ "$size" != 0 && "$actual" != "$size" ]]; then
        rm -f "$tmp"
        die "$name: got $actual bytes, expected $size (partial/corrupt download removed - re-run the installer)"
    fi
    if [[ "$size" == 0 && "$actual" -lt 1000000 ]]; then
        rm -f "$tmp"
        die "$name: downloaded file is too small ($actual bytes) - partial/corrupt download removed"
    fi
    magic=$(head -c 2 "$tmp" | od -An -tx1 | tr -d ' \n')
    case "$name" in
        *.onnx) [[ "$magic" == 08* ]]   || { rm -f "$tmp"; die "$name is not an ONNX protobuf (magic $magic)"; } ;;
        *.bin)  [[ "$magic" == 504b ]]  || { rm -f "$tmp"; die "$name is not an NPZ archive (magic $magic)"; } ;;
    esac
    mv -f "$tmp" "$dest"
    ok "downloaded $name ($actual bytes)"
}

fetch_models() {
    (( SKIP_MODELS )) && { info "skipping model downloads (--skip-models)"; return 0; }
    local m
    for m in $(tr ',' ' ' <<<"$MODELS"); do download "$m"; done
    download voices
}

# --- configuration, units, trigger -------------------------------------------------------------
write_config() {
    mkdir -p "$CONFIG_DIR"
    local provider
    case "$HW" in nvidia) provider=cuda ;; amd) provider=rocm ;; intel) provider=openvino ;; *) provider=cpu ;; esac
    if [[ -f "$CONFIG_FILE" ]]; then
        "$VENV_PY" "$MAIN_PY" config --write "$CONFIG_FILE.new" --force >/dev/null
        info "kept existing $CONFIG_FILE (fresh template written to $CONFIG_FILE.new)"
        return 0
    fi
    "$VENV_PY" "$MAIN_PY" config --write "$CONFIG_FILE" >/dev/null
    sed -i "s/^provider = \"auto\"/provider = \"$provider\"/" "$CONFIG_FILE"
    if [[ "$HW" == amd ]]; then
        sed -i 's/^# MIOPEN_FIND_MODE = "FAST"/MIOPEN_FIND_MODE = "FAST"/' "$CONFIG_FILE"
        if [[ -n "$HSA_OVERRIDE" ]]; then
            sed -i "s/^# HSA_OVERRIDE_GFX_VERSION = .*/HSA_OVERRIDE_GFX_VERSION = \"$HSA_OVERRIDE\"/" "$CONFIG_FILE"
        fi
    fi
    ok "wrote $CONFIG_FILE (provider = $provider)"
}

write_units() {
    (( NO_SYSTEMD )) && { info "skipping systemd units (--no-systemd)"; return 0; }
    have systemctl || { warn "systemctl not found - skipping units"; return 0; }
    mkdir -p "$UNIT_DIR"
    cat > "$UNIT_DIR/dusky-kokoro.socket" <<EOF
# Generated by kokoro_installer.sh $INSTALLER_VERSION
[Unit]
Description=Dusky Kokoro TTS control socket
Documentation=file://$MAIN_PY

[Socket]
ListenStream=%t/dusky-kokoro/control.sock
SocketMode=0600
DirectoryMode=0700
Backlog=64
RemoveOnStop=yes

[Install]
WantedBy=sockets.target
EOF
    cat > "$UNIT_DIR/dusky-kokoro.service" <<EOF
# Generated by kokoro_installer.sh $INSTALLER_VERSION
[Unit]
Description=Dusky Kokoro TTS daemon (Kokoro-ONNX, socket-activated, exits when idle)
Requires=dusky-kokoro.socket
After=dusky-kokoro.socket pipewire.service wireplumber.service pulseaudio.service
PartOf=graphical-session.target

[Service]
Type=notify
NotifyAccess=main
ExecStart=$VENV_PY -X utf8 -u $MAIN_PY daemon
WorkingDirectory=$DUSKY_HOME
Environment=PYTHONUNBUFFERED=1
Environment=DUSKY_CONFIG=%E/dusky-kokoro/config.toml
Restart=on-failure
RestartSec=1
TimeoutStartSec=120
TimeoutStopSec=10
KillMode=mixed
NoNewPrivileges=yes
UMask=0077
OOMScoreAdjust=100

[Install]
# Socket-activated on purpose: enable dusky-kokoro.socket, not this unit.
EOF
    systemctl --user daemon-reload
    systemctl --user stop dusky-kokoro.service >/dev/null 2>&1 || true
    systemctl --user reset-failed dusky-kokoro.service >/dev/null 2>&1 || true
    systemctl --user enable --now dusky-kokoro.socket
    ok "systemd: dusky-kokoro.socket enabled ($(systemctl --user is-active dusky-kokoro.socket))"
}

install_trigger() {
    if [[ "$SCRIPT_DIR/trigger.sh" -ef "$TRIGGER_DIR/trigger.sh" ]]; then
        chmod 755 "$TRIGGER_DIR/trigger.sh"
        ok "trigger.sh already in place ($TRIGGER_DIR/trigger.sh)"
    else
        install -Dm755 "$SCRIPT_DIR/trigger.sh" "$TRIGGER_DIR/trigger.sh"
        ok "installed $TRIGGER_DIR/trigger.sh"
    fi
    if [[ -d "$HOME/.local/bin" ]]; then
        ln -sfn "$TRIGGER_DIR/trigger.sh" "$HOME/.local/bin/dusky-kokoro"
        ok "symlinked ~/.local/bin/dusky-kokoro"
        if [[ -f "$SCRIPT_DIR/tui_kokoro.py" ]]; then
            chmod 755 "$SCRIPT_DIR/tui_kokoro.py"
            ln -sfn "$SCRIPT_DIR/tui_kokoro.py" "$HOME/.local/bin/dusky-kokoro-tui"
            ok "symlinked ~/.local/bin/dusky-kokoro-tui (Python Textual TUI)"
        elif [[ -f "$SCRIPT_DIR/tui/kokoro_tui.sh" ]]; then
            chmod 755 "$SCRIPT_DIR/tui/kokoro_tui.sh"
            ln -sfn "$SCRIPT_DIR/tui/kokoro_tui.sh" "$HOME/.local/bin/dusky-kokoro-tui"
            ok "symlinked ~/.local/bin/dusky-kokoro-tui (Bash fallback)"
        fi
    fi
}

self_test() {
    (( SKIP_SELFTEST )) && { info "skipping self test (--skip-selftest)"; return 0; }
    if (( SKIP_MODELS )); then
        info "self test: running doctor diagnostics (skipping synth benchmark because models were skipped)"
        DUSKY_HOME="$DUSKY_HOME" "$VENV_PY" "$MAIN_PY" doctor || true
        return 0
    fi
    info "self test: doctor + offline synthesis benchmark"
    if DUSKY_HOME="$DUSKY_HOME" "$VENV_PY" "$MAIN_PY" doctor --synth; then
        ok "self test passed"
    else
        warn "self test reported problems (see above); fix them, then run: trigger.sh --doctor --synth"
    fi
}

summary() {
    echo
    echo "=============================================================================="
    echo " Dusky Kokoro TTS $INSTALLER_VERSION installed  (mode: $HW)"
    echo "=============================================================================="
    echo "  install dir : $DUSKY_HOME"
    echo "  config      : $CONFIG_FILE"
    echo "  trigger     : $TRIGGER_DIR/trigger.sh"
    echo "  socket      : \$XDG_RUNTIME_DIR/dusky-kokoro/control.sock"
    echo
    echo "  try it      : $TRIGGER_DIR/trigger.sh --text 'Dusky Kokoro is installed.'"
    echo "  hotkey      : bind '$TRIGGER_DIR/trigger.sh' (clipboard) and '... --pause'"
    echo "  status/logs : trigger.sh --status | trigger.sh --logs | trigger.sh --doctor"
    echo "  voices      : trigger.sh --voices     (edit [voice] spec in config.toml, then trigger.sh --reload)"
    echo "=============================================================================="
}

# --- main ----------------------------------------------------------------------------------------
info "Dusky Kokoro installer $INSTALLER_VERSION"
preflight
scan_gpus
choose_hw
choose_models
check_hw_prereqs
setup_env
verify_runtime
fetch_models
write_config
write_units
install_trigger
self_test
summary
