#!/usr/bin/env bash
# =============================================================================
#  kokoro_installer.sh - Dusky Kokoro TTS installer
#  Target: Arch Linux (rolling), CPython 3.14 managed by uv, systemd user session
#
#  What it does
#    1. scans GPUs through sysfs (vendor/class ids) and lspci, checks drivers
#    2. writes a per-hardware pyproject.toml and builds a locked, isolated venv
#       (uv lock + uv sync) in DUSKY_HOME - no --force-reinstall hacks:
#         * kokoro-onnx metadata is overridden with [[tool.uv.dependency-metadata]]
#           (drops its unconditional CPU "onnxruntime" pin, lifts its <3.14 cap)
#         * exactly ONE onnxruntime distribution ends up installed
#    3. downloads tested Kokoro ONNX exports + voices with resume, retry,
#       exact-size, checksum (where recorded), and tensor verification
#    4. writes config.toml (generated by the daemon itself), the systemd
#       socket + service units, and installs trigger.sh
#    5. runs an end-to-end self test (providers, model load, synthesis, RTF)
#
#  Usage: kokoro_installer.sh [--hw nvidia|amd|intel|cpu] [--models LIST|all]
#         [--rocm-source amd|arch] [--hsa-override 10.3.0]
#         [--home DIR] [--trigger-dir DIR] [--install-system-deps] [--no-systemd]
#         [--offline] [--upgrade] [--ort-wheel PATH]
#         [--skip-models] [--skip-selftest] [--yes] [--uninstall] [--help]
#
#  Style note: no brace parameter expansions are used on purpose (see trigger.sh).
# =============================================================================
set -Eeuo pipefail
shopt -s inherit_errexit

INSTALLER_VERSION="5.1.2"
PY_SERIES="3.14"
KOKORO_ONNX_VERSION="0.6.1"     # pinned; its metadata is overridden below (see write_pyproject)
ORT_MIN="1.27"
RELEASE_BASE="https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.1"

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

DUSKY_HOME=$(printenv DUSKY_HOME || true)
[[ -n "$DUSKY_HOME" ]] || DUSKY_HOME="$HOME/contained_apps/uv/dusky_kokoro"
TRIGGER_DIR=$(printenv DUSKY_TRIGGER_DIR || true)
[[ -n "$TRIGGER_DIR" ]] || TRIGGER_DIR="$HOME/user_scripts/tts_stt/dusky_kokoro"
CONFIG_HOME=$(printenv XDG_CONFIG_HOME || true)
[[ -n "$CONFIG_HOME" ]] || CONFIG_HOME="$HOME/.config"

HW=""                 # nvidia | amd | intel | cpu
MODELS=""             # comma separated: fp16-gpu,f32,int8,fp16 | all
ROCM_SOURCE="amd"     # amd = isolated --ort-wheel installation
                      # arch = inherit a system MIGraphX build
HSA_OVERRIDE=""       # explicit hardware override, only when supplied by the user
ASSUME_YES=0
VERBOSE=0
INSTALL_LOG=""
CURRENT_STEP="startup"
NO_SYSTEMD=0
SKIP_MODELS=0
SKIP_SELFTEST=0
INSTALL_SYSTEM_DEPS=0
OFFLINE=0
UPGRADE=0
ORT_WHEEL=""
UNINSTALL=0

GPU_NVIDIA=0
GPU_AMD=0
GPU_INTEL=0

# --- output helpers -------------------------------------------------------------
if [[ -t 1 ]]; then
    C_INFO=$'\e[1;34m'; C_OK=$'\e[1;32m'; C_WARN=$'\e[1;33m'; C_ERR=$'\e[1;31m'; C_END=$'\e[0m'
else
    C_INFO=""; C_OK=""; C_WARN=""; C_ERR=""; C_END=""
fi
info() { printf '%s::%s %s\n' "$C_INFO" "$C_END" "$*"; }
ok()   { printf '%s [ok]%s %s\n' "$C_OK" "$C_END" "$*"; }
warn() { printf '%s [!!]%s %s\n' "$C_WARN" "$C_END" "$*" >&2; }
die()  { printf '%s [xx]%s %s\n' "$C_ERR" "$C_END" "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }
installer_error() {
    local status="$1" line="$2"
    if [[ -n "$INSTALL_LOG" && -f "$INSTALL_LOG" ]]; then
        (( VERBOSE )) || tail -n 20 "$INSTALL_LOG" >&2
        printf '\n' >&2
        die "$CURRENT_STEP failed (exit $status). Log: $INSTALL_LOG"
    fi
    die "installer failed at line $line (exit $status)"
}
trap 'installer_error "$?" "$LINENO"' ERR

run_step() {
    CURRENT_STEP="$1"
    shift
    info "$CURRENT_STEP"
    # Keep errexit active inside each step. Testing a shell function with `if`
    # would disable it throughout the function and could hide installation errors.
    if (( VERBOSE )); then
        (trap - ERR; "$@") 2>&1 | tee -a "$INSTALL_LOG"
    else
        (trap - ERR; "$@") >>"$INSTALL_LOG" 2>&1
    fi
}

show_help() {
    cat <<'HELP'
Dusky Kokoro · speech setup

  Usage  kokoro_installer.sh [OPTIONS]
  Quick  kokoro_installer.sh --yes

Setup
  --hw BACKEND          nvidia | cpu | amd | intel (default: detect)
  -y, --yes             Use recommended defaults without prompts
  --offline             Use cached packages and models
  --upgrade             Refresh dependencies (online)
  --install-system-deps Install missing Arch packages with sudo

Locations & runtimes
  --home DIR            Python environment and models
  --trigger-dir DIR     Desktop scripts
  --ort-wheel PATH      Custom ONNX Runtime wheel (AMD/Intel)
  --rocm-source SOURCE  amd (custom wheel) | arch (system runtime)
  --hsa-override VALUE  Explicit AMD architecture override
  --models LIST         fp16-gpu,int8,f32,fp16 | all

Other
  --no-systemd          Skip the on-demand service
  --skip-models         Keep existing models
  --skip-selftest       Skip synthesis verification
  --verbose             Show detailed installation output
  --uninstall           Remove installation; keep config and archives
  -h, --help            Show this help

AMD/Intel acceleration requires a matching runtime. CPU works without one.
HELP
}

# --- argument parsing -------------------------------------------------------------
while (( $# > 0 )); do
    case "$1" in
        -h|--help)             show_help; exit 0 ;;
        --hw)                  (( $# >= 2 )) || die "--hw needs an argument"; HW="$2"; shift ;;
        --models)              (( $# >= 2 )) || die "--models needs an argument"; MODELS="$2"; shift ;;
        --rocm-source)         (( $# >= 2 )) || die "--rocm-source needs an argument"; ROCM_SOURCE="$2"; shift ;;
        --hsa-override)        (( $# >= 2 )) || die "--hsa-override needs an argument"; HSA_OVERRIDE="$2"; shift ;;
        --home)                (( $# >= 2 )) || die "--home needs an argument"; DUSKY_HOME="$2"; shift ;;
        --trigger-dir)         (( $# >= 2 )) || die "--trigger-dir needs an argument"; TRIGGER_DIR="$2"; shift ;;
        -y|--yes)              ASSUME_YES=1 ;;
        --verbose)            VERBOSE=1 ;;
        --no-systemd)          NO_SYSTEMD=1 ;;
        --skip-models)         SKIP_MODELS=1 ;;
        --skip-selftest)       SKIP_SELFTEST=1 ;;
        --install-system-deps) INSTALL_SYSTEM_DEPS=1 ;;
        --offline)            OFFLINE=1; export UV_OFFLINE=1 ;;
        --upgrade)            UPGRADE=1 ;;
        --ort-wheel)          (( $# >= 2 )) || die "--ort-wheel needs a path"; ORT_WHEEL=$(realpath -e -- "$2"); shift ;;
        --uninstall)           UNINSTALL=1 ;;
        *)                     die "unknown option: $1 (see --help)" ;;
    esac
    shift
done

case "$HW" in ""|nvidia|amd|intel|cpu) ;; *) die "--hw must be nvidia, amd, intel or cpu" ;; esac
case "$ROCM_SOURCE" in amd|arch) ;; *) die "--rocm-source must be amd or arch" ;; esac

CONFIG_DIR="$CONFIG_HOME/dusky-kokoro"
CONFIG_FILE=$(printenv DUSKY_CONFIG || true)
[[ -n "$CONFIG_FILE" ]] || CONFIG_FILE="$CONFIG_DIR/config.toml"
export DUSKY_CONFIG="$CONFIG_FILE"
DUSKY_HOME=$(realpath -m -- "$DUSKY_HOME")
TRIGGER_DIR=$(realpath -m -- "$TRIGGER_DIR")
(( OFFLINE && UPGRADE )) && die "--upgrade cannot be combined with --offline"
UNIT_DIR="$CONFIG_HOME/systemd/user"
MODEL_DIR="$DUSKY_HOME/models"
VENV_PY="$DUSKY_HOME/.venv/bin/python"
MAIN_PY="$DUSKY_HOME/dusky_main.py"

# --- model manifest (exact byte sizes from the GitHub release API) ---------------------
model_file() {
    case "$1" in
        f32)      echo "kokoro-v1.0.onnx" ;;
        fp16)     echo "kokoro-v1.0.fp16.onnx" ;;
        fp16-gpu) echo "kokoro-v1.0.fp16-gpu.onnx" ;;
        int8)     echo "kokoro-v1.0.int8.onnx" ;;
        voices)   echo "voices-v1.0.bin" ;;
        *)        return 1 ;;
    esac
}
model_size() {
    case "$1" in
        f32)      echo 325505369 ;;
        fp16)     echo 163527961 ;;
        fp16-gpu) echo 177464787 ;;
        int8)     echo 92361271 ;;
        voices)   echo 28214398 ;;
        *)        return 1 ;;
    esac
}

# --- uninstall -------------------------------------------------------------------------
if (( UNINSTALL )); then
    info "uninstalling Dusky Kokoro"
    if have systemctl; then
        systemctl --user disable --now dusky_kokoro.socket dusky-kokoro.socket >/dev/null 2>&1 || true
        systemctl --user stop dusky_kokoro.service dusky-kokoro.service dusky_kokoro_adhoc.service dusky-kokoro-adhoc.service >/dev/null 2>&1 || true
        rm -f "$UNIT_DIR/dusky_kokoro.socket" "$UNIT_DIR/dusky_kokoro.service" "$UNIT_DIR/dusky-kokoro.socket" "$UNIT_DIR/dusky-kokoro.service"
        systemctl --user daemon-reload >/dev/null 2>&1 || true
    fi
    rm -f "$TRIGGER_DIR/trigger.sh" "$HOME/.local/bin/dusky-kokoro" "$HOME/.local/bin/dusky-kokoro-tui"
    if (( ASSUME_YES )) || { [[ -t 0 ]] && read -r -p "remove $DUSKY_HOME (venv + models)? [y/N] " a && [[ "$a" == y* ]]; }; then
        rm -rf "$DUSKY_HOME"
        ok "removed $DUSKY_HOME"
    fi
    info "kept $CONFIG_FILE and $HOME/.cache/dusky-kokoro (remove manually if desired)"
    exit 0
fi

# --- preflight --------------------------------------------------------------------------
preflight() {
    [[ "$(printf '%s\n' 5.3.20 "$BASH_VERSION" | sort -V | head -n 1)" == 5.3.20 ]] || die "Bash >= 5.3.20 is required"
    [[ -f /etc/arch-release ]] || warn "not an Arch Linux system - continuing, package hints will not apply"
    [[ -f "$SCRIPT_DIR/dusky_main.py" ]] || die "dusky_main.py must sit next to this installer ($SCRIPT_DIR)"
    [[ -f "$SCRIPT_DIR/trigger.sh" ]] || die "missing $SCRIPT_DIR/trigger.sh; update the complete dusky_kokoro directory"

    local missing=""
    have curl || missing="$missing curl"
    have mpv  || missing="$missing mpv"
    have notify-send || missing="$missing libnotify"
    have wl-paste || missing="$missing wl-clipboard"
    have pdftotext || missing="$missing poppler"
    if [[ -n "$missing" ]]; then
        if (( INSTALL_SYSTEM_DEPS )) && have pacman; then
            info "installing missing system packages via pacman:$missing"
            read -r -a _missing_arr <<< "$missing"
            local -a pacman_flags=(-S --needed --noconfirm)
            (( OFFLINE )) && die "offline mode needs system packages preinstalled on the ISO:$missing"
            sudo pacman "${pacman_flags[@]}" "${_missing_arr[@]}"
        else
            die "missing system packages:$missing (preinstall on the ISO, or use --install-system-deps online)"
        fi
    fi
    if ! have uv; then
        if ! (( INSTALL_SYSTEM_DEPS && ! OFFLINE )) || ! have pacman; then
            die "uv missing; preinstall it or use --install-system-deps online"
        fi
        sudo pacman -S --needed --noconfirm uv
    fi
    command -v python3 >/dev/null || die "Python $PY_SERIES is required"
    python3 -c 'import sys; assert sys.version_info >= (3, 14, 7)' || die "Python >= 3.14.7 is required"
}

# --- hardware scan ----------------------------------------------------------------------
scan_gpus() {
    local dev vendor class
    for dev in /sys/class/drm/card[0-9]*/device; do
        [[ -r "$dev/vendor" && -r "$dev/class" ]] || continue
        vendor=$(<"$dev/vendor")
        class=$(<"$dev/class")
        case "$class" in 0x0300*|0x0302*|0x0380*) ;; *) continue ;; esac
        case "$vendor" in
            0x10de) GPU_NVIDIA=1 ;;
            0x1002) GPU_AMD=1 ;;
            0x8086) GPU_INTEL=1 ;;
        esac
    done
    local -a detected=()
    (( GPU_NVIDIA )) && detected+=(NVIDIA)
    (( GPU_AMD )) && detected+=(AMD)
    (( GPU_INTEL )) && detected+=(Intel)
    info "Detected: ${detected[*]:-CPU only}"
}

choose_hw() {
    local default="cpu"
    if (( GPU_NVIDIA )) && [[ -r /proc/driver/nvidia/version ]] && have nvidia-smi; then
        local caps
        caps=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null || true)
        if [[ -n "$caps" ]] && awk '($1+0) < 7.5 { exit 1 }' <<< "$caps"; then
            default="nvidia"
        else
            warn "current CUDA 13 libraries require Turing or newer; selecting CPU for this GPU"
        fi
    fi
    # AMD/Intel acceleration needs a matching Python 3.14 runtime build.
    # CPU remains the portable automatic choice until that build is supplied.

    if [[ -n "$HW" ]]; then return 0; fi
    if (( ASSUME_YES )) || [[ ! -t 0 ]]; then HW="$default"; return 0; fi
    echo
    local number=4
    [[ "$default" == nvidia ]] && number=1
    printf '  Backend\n'
    printf '  1  NVIDIA CUDA%s\n' "$([[ "$number" == 1 ]] && printf '  · recommended')"
    printf '  2  AMD MIGraphX    · custom runtime\n'
    printf '  3  Intel OpenVINO  · custom runtime\n'
    printf '  4  CPU%s\n\n' "$([[ "$number" == 4 ]] && printf '  · recommended')"
    local answer
    read -r -e -p "  Choose [$number]: " answer || answer=""
    case "$answer" in
        1) HW=nvidia ;; 2) HW=amd ;; 3) HW=intel ;; 4) HW=cpu ;; "") HW="$default" ;;
        *) die "invalid choice" ;;
    esac
}

choose_models() {
    local default
    case "$HW" in intel) default="f32,int8" ;; *) default="fp16-gpu,int8" ;; esac
    [[ -n "$MODELS" ]] || MODELS="$default"
    [[ "$MODELS" == all ]] && MODELS="fp16-gpu,f32,int8,fp16"
    [[ -n "$MODELS" && "$MODELS" != ,* && "$MODELS" != *, && "$MODELS" != *,,* ]] || die "--models must be a nonempty comma-separated list"
    local m
    for m in $(tr ',' ' ' <<<"$MODELS"); do model_file "$m" >/dev/null || die "unknown model precision '$m'"; done
}

# --- per-hardware prerequisites ---------------------------------------------------------------
check_hw_prereqs() {
    case "$HW" in
        nvidia)
            [[ -r /proc/driver/nvidia/version ]] || die "NVIDIA kernel driver not loaded (sudo pacman -S nvidia-open nvidia-utils; reboot)"
            ;;
        amd)
            if [[ "$ROCM_SOURCE" == arch ]]; then
                python3 -c 'import onnxruntime as o; assert "MIGraphXExecutionProvider" in o.get_available_providers()' \
                    || die "system Python needs a current ONNX Runtime build with MIGraphXExecutionProvider; use --ort-wheel or --hw cpu"
            else
                [[ -n "$ORT_WHEEL" ]] || die "AMD acceleration needs --ort-wheel PATH for Python 3.14/MIGraphX and matching ROCm libraries, or --rocm-source arch. Use --hw cpu otherwise."
            fi
            [[ -e /dev/kfd ]] || warn "/dev/kfd missing - amdgpu KFD not available, ROCm will not work"
            id -nG | grep -qw render || warn "user is not in the 'render' group (sudo usermod -aG render,video $USER; re-login)"

            ;;
        intel)
            [[ -n "$ORT_WHEEL" ]] || die "PyPI onnxruntime-openvino has no Python 3.14 Linux wheel; supply --ort-wheel PATH from an OpenVINO-enabled build, or use --hw cpu"
            ls /dev/dri/renderD* >/dev/null 2>&1 || warn "no /dev/dri/renderD* node - OpenVINO GPU device unavailable (CPU device still works)"
            pacman -Q intel-compute-runtime >/dev/null 2>&1 || warn "intel-compute-runtime not installed: OpenVINO GPU plugin needs it (sudo pacman -S intel-compute-runtime)"
            ;;
        cpu) ;;
    esac
}

# --- python environment -----------------------------------------------------------------------
write_pyproject() {
    local ort_line="" index_block="" ort_name=""
    if [[ -n "$ORT_WHEEL" ]]; then
        ort_name=$(python3 - "$ORT_WHEEL" <<'PYMETA'
import email, sys, zipfile
with zipfile.ZipFile(sys.argv[1]) as z:
    name = next(n for n in z.namelist() if n.endswith('.dist-info/METADATA'))
    m = email.message_from_bytes(z.read(name))
    package = m['Name']
    if not package.startswith('onnxruntime'):
        raise SystemExit('wheel must contain ONNX Runtime')
    print(package)
PYMETA
)
        ort_line="    \"$ort_name>=$ORT_MIN\","
        index_block=$(python3 - "$ort_name" "$ORT_WHEEL" <<'PYSOURCE'
import json,sys
print('\n[tool.uv.sources]\n' + json.dumps(sys.argv[1]) + ' = { path = ' + json.dumps(sys.argv[2]) + ' }')
PYSOURCE
)
    else
        case "$HW" in
            nvidia) ort_line="    \"onnxruntime-gpu[cuda,cudnn]>=$ORT_MIN\"," ;;
            amd) ;; # Arch system runtime is inherited by the venv.
            cpu) ort_line="    \"onnxruntime>=$ORT_MIN\"," ;;
        esac
    fi
    cat > "$DUSKY_HOME/pyproject.toml" <<EOF
# Generated by kokoro_installer.sh $INSTALLER_VERSION - hardware mode: $HW
# Re-run the installer to switch hardware modes; "uv sync" reconciles the environment.
[project]
name = "dusky-kokoro"
version = "$INSTALLER_VERSION"
description = "Dusky Kokoro TTS daemon environment ($HW)"
requires-python = ">=3.14.7"
dependencies = [
    "kokoro-onnx==$KOKORO_ONNX_VERSION",
    "numpy>=2.3",
$ort_line
]

[tool.uv]
package = false
$index_block

# kokoro-onnx $KOKORO_ONNX_VERSION declares requires-python "<3.14" (its own CI cap, the code is pure
# Python) and an UNCONDITIONAL dependency on the CPU "onnxruntime" wheel. Installing that next to
# onnxruntime-gpu / -rocm / -openvino makes two distributions write the same "onnxruntime/"
# package directory - the root cause of the old --force-reinstall hack. uv lets us replace the
# declared metadata of exactly this package, so precisely one onnxruntime distribution is resolved.
[[tool.uv.dependency-metadata]]
name = "kokoro-onnx"
version = "$KOKORO_ONNX_VERSION"
requires-python = ">=3.10"
requires-dist = [
    "espeakng-loader>=0.2.4",
    "phonemizer>=3.4.0",
    "numpy>=2.0.2",
]
EOF
    ok "wrote $DUSKY_HOME/pyproject.toml"
}

setup_env() {
    mkdir -p "$DUSKY_HOME" "$MODEL_DIR"
    write_pyproject
    cd "$DUSKY_HOME"
    if ! uv python find "$PY_SERIES" >/dev/null 2>&1; then
        info "ensuring CPython $PY_SERIES (uv-managed)"
        (( OFFLINE )) && die "offline mode requires Python $PY_SERIES preinstalled or cached by uv"
        uv python install "$PY_SERIES"
    else
        info "using CPython $PY_SERIES: $(uv python find "$PY_SERIES")"
    fi
    local python_request="$PY_SERIES"
    if [[ "$HW" == amd && "$ROCM_SOURCE" == arch ]]; then
        python_request=$(command -v python3)
        uv venv --allow-existing --python "$python_request" --system-site-packages
    else
        if [[ ! -d .venv ]]; then uv venv --python "$python_request"; fi
        if [[ -f .venv/pyvenv.cfg ]]; then
            sed -i 's/^include-system-site-packages = true/include-system-site-packages = false/' .venv/pyvenv.cfg
        fi
    fi
    printf '%s\n' "$python_request" > .python-version
    info "resolving (uv lock) and syncing the environment"
    if (( UPGRADE )); then uv lock --upgrade; else uv lock; fi
    uv sync --locked --python "$python_request"
    if [[ ! "$SCRIPT_DIR/dusky_main.py" -ef "$MAIN_PY" ]]; then
        install -m 644 "$SCRIPT_DIR/dusky_main.py" "$MAIN_PY"
    fi
    ok "environment ready: $VENV_PY ($("$VENV_PY" --version))"
}

verify_runtime() {
    local expected providers count
    case "$HW" in
        nvidia) expected="CUDAExecutionProvider" ;;
        amd)    expected="MIGraphXExecutionProvider" ;;
        intel)  expected="OpenVINOExecutionProvider" ;;
        cpu)    expected="CPUExecutionProvider" ;;
    esac
    cd "$DUSKY_HOME"
    count=$(uv pip list 2>/dev/null | grep -ciE '^onnxruntime' || true)
    if [[ "$HW" == amd && "$ROCM_SOURCE" == arch ]]; then
        (( count == 0 )) || warn "an onnxruntime wheel is installed in the venv although --rocm-source arch was requested"
    else
        (( count == 1 )) || die "expected exactly one onnxruntime distribution in the venv, found $count"
    fi
    providers=$("$VENV_PY" -c 'import onnxruntime as o; hasattr(o, "preload_dlls") and o.preload_dlls(); print(" ".join(o.get_available_providers()))')
    info "onnxruntime providers: $providers"
    if grep -qw "$expected" <<<"$providers"; then
        ok "$expected is available"
    else
        die "$expected is NOT part of this onnxruntime build; select a matching wheel or --hw cpu"
    fi
}

# --- models -------------------------------------------------------------------------------------
download() {  # key
    local key="$1" name size url dest tmp actual magic
    name=$(model_file "$key")
    size=$(model_size "$key")
    url="$RELEASE_BASE/$name"
    [[ "$key" == fp16-gpu || "$key" == int8 ]] && url="https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/$name"
    dest="$MODEL_DIR/$name"
    tmp="$dest.part"
    if [[ -f "$dest" ]]; then
        actual=$(stat -c %s "$dest")
        if [[ "$actual" == "$size" ]]; then
            if verify_model "$dest" "$key"; then
                ok "present: $name ($actual bytes)"
                return 0
            fi
            warn "$name failed validation"
        else
            warn "$name has $actual bytes (expected $size)"
        fi
    fi
    if [[ -f "$tmp" && $(stat -c %s "$tmp") -ge "$size" ]]; then
        if [[ $(stat -c %s "$tmp") == "$size" ]] && verify_model "$tmp" "$key"; then
            mv -f "$tmp" "$dest"
            ok "recovered complete download: $name"
            return 0
        fi
        (( OFFLINE )) && die "offline mode requires a valid model at $dest or $tmp"
        rm -f "$tmp"
    fi
    (( OFFLINE )) && die "offline mode requires a valid model at $dest or $tmp"
    info "downloading $name"
    curl --fail --location --retry 5 --retry-all-errors --retry-delay 2 --continue-at - \
         --progress-bar --output "$tmp" "$url"
    actual=$(stat -c %s "$tmp")
    if [[ "$actual" != "$size" ]]; then
        rm -f "$tmp"
        die "$name: got $actual bytes, expected $size (partial/corrupt download removed - re-run the installer)"
    fi
    magic=$(head -c 2 "$tmp" | od -An -tx1 | tr -d ' \n')
    case "$name" in
        *.onnx) [[ "$magic" == 08* ]]   || { rm -f "$tmp"; die "$name is not an ONNX protobuf (magic $magic)"; } ;;
        *.bin)  [[ "$magic" == 504b ]]  || { rm -f "$tmp"; die "$name is not an NPZ archive (magic $magic)"; } ;;
    esac
    if ! verify_model "$tmp" "$key"; then
        rm -f "$tmp"
        die "$name failed validation (invalid partial download removed - re-run the installer)"
    fi
    mv -f "$tmp" "$dest"
    ok "downloaded $name ($actual bytes)"
}

verify_model() {
    "$VENV_PY" - "$1" "$2" <<'PYVERIFY'
import sys, hashlib
from pathlib import Path
p = Path(sys.argv[1])
expected = {
    'fp16-gpu': 'c1610a859f3bdea01107e73e50100685af38fff88f5cd8e5c56df109ec880204',
    'f32': 'beb0d1848dee9a49da392cc3df26958d46cfa35d321edf434f52949153f0df3a',
    'fp16': 'f3a290d384fbb27966d462905c71a46cef9e5fd00516b40df32a0b4afe77ac96',
    'int8': '6e742170d309016e5891a994e1ce1559c702a2ccd0075e67ef7157974f6406cb',
    'voices': 'bca610b8308e8d99f32e6fe4197e7ec01679264efed0cac9140fe9c29f1fbf7d',
}.get(sys.argv[2])
if expected:
    with p.open('rb') as f:
        actual = hashlib.file_digest(f, 'sha256').hexdigest()
    if actual != expected:
        raise SystemExit(f'model checksum mismatch: {p}')
if sys.argv[2] == 'voices':
    import numpy as np
    with np.load(p, allow_pickle=False) as voices:
        if len(voices.files) != 54:
            raise SystemExit('voices archive must contain 54 styles')
        for name in voices.files:
            v = voices[name]
            if v.shape != (510, 1, 256) or not np.isfinite(v).all():
                raise SystemExit(f'invalid voice tensor: {name}')
else:
    with p.open('rb') as f:
        if f.read(1) != b'\x08':
            raise SystemExit(f'invalid ONNX protobuf: {p}')
PYVERIFY
}

fetch_models() {
    (( SKIP_MODELS )) && { info "skipping model downloads (--skip-models)"; return 0; }
    local m
    for m in $(tr ',' ' ' <<<"$MODELS"); do download "$m"; done
    download voices
}

# --- configuration, units, trigger -------------------------------------------------------------
write_config() {
    mkdir -p "$CONFIG_DIR"
    local provider
    case "$HW" in nvidia) provider=cuda ;; amd) provider=migraphx ;; intel) provider=openvino ;; *) provider=cpu ;; esac
    if [[ -f "$CONFIG_FILE" ]]; then
        "$VENV_PY" "$MAIN_PY" config >/dev/null
        "$VENV_PY" "$MAIN_PY" config --write "$CONFIG_FILE.new" --force >/dev/null
        info "kept existing $CONFIG_FILE (fresh template written to $CONFIG_FILE.new)"
        return 0
    fi
    "$VENV_PY" "$MAIN_PY" config --write "$CONFIG_FILE" >/dev/null
    sed -i "s/^provider = \"auto\"/provider = \"$provider\"/" "$CONFIG_FILE"
    if [[ "$HW" == amd ]]; then
        if [[ -n "$HSA_OVERRIDE" ]]; then
            sed -i "s/^# HSA_OVERRIDE_GFX_VERSION = .*/HSA_OVERRIDE_GFX_VERSION = \"$HSA_OVERRIDE\"/" "$CONFIG_FILE"
        fi
    fi
    ok "wrote $CONFIG_FILE (provider = $provider)"
}

write_units() {
    (( NO_SYSTEMD )) && { info "skipping systemd units (--no-systemd)"; return 0; }
    have systemctl || { warn "systemctl not found - skipping units"; return 0; }
    mkdir -p "$UNIT_DIR"
    local unit_home unit_py unit_main unit_config unit_socket unit_socket_arg socket_path
    socket_path=$("$VENV_PY" - "$MAIN_PY" "$CONFIG_FILE" <<'PYSOCKET'
import importlib.util,sys
from pathlib import Path
spec = importlib.util.spec_from_file_location("dusky", sys.argv[1])
m = importlib.util.module_from_spec(spec); sys.modules[spec.name] = m; spec.loader.exec_module(m)
p = Path(sys.argv[2])
print(m.resolve_paths(m.load_config(p), p).socket)
PYSOCKET
)
    mapfile -t _unit_paths < <(python3 - "$DUSKY_HOME" "$VENV_PY" "$MAIN_PY" "$CONFIG_FILE" "$socket_path" "$socket_path" <<'PYUNIT'
import os,sys
for index, path in enumerate(sys.argv[1:]):
    home = os.path.expanduser('~')
    runtime = os.environ.get('XDG_RUNTIME_DIR') or f'/run/user/{os.getuid()}'
    if index in (4, 5) and path.startswith(runtime + '/'):
        path = '%t/' + path[len(runtime)+1:].replace('%', '%%')
    elif path.startswith(home + '/'):
        path = '%h/' + path[len(home)+1:].replace('%', '%%')
    else:
        path = path.replace('%', '%%')
    path = path.replace('\\', '\\\\').replace('"', '\\"')
    if index in (1, 2, 3, 5):
        path = path.replace('$', '$$')
    print(path if index in (0, 4) else '"' + path + '"')
PYUNIT
)
    unit_home="${_unit_paths[0]}"; unit_py="${_unit_paths[1]}"; unit_main="${_unit_paths[2]}"; unit_config="${_unit_paths[3]}"; unit_socket="${_unit_paths[4]}"; unit_socket_arg="${_unit_paths[5]}"
    cat > "$UNIT_DIR/dusky_kokoro.socket" <<EOF
# Generated by kokoro_installer.sh $INSTALLER_VERSION
[Unit]
Description=Dusky Kokoro TTS control socket

[Socket]
ListenStream=$unit_socket
SocketMode=0600
DirectoryMode=0700
Backlog=64
RemoveOnStop=yes

[Install]
WantedBy=sockets.target
EOF
    cat > "$UNIT_DIR/dusky_kokoro.service" <<EOF
# Generated by kokoro_installer.sh $INSTALLER_VERSION
[Unit]
Description=Dusky Kokoro TTS daemon (Kokoro-ONNX, socket-activated, exits when idle)
Requires=dusky_kokoro.socket
After=dusky_kokoro.socket pipewire.service wireplumber.service pulseaudio.service
PartOf=graphical-session.target

[Service]
Type=notify
NotifyAccess=main
ExecStart=$unit_py -X utf8 -u $unit_main --config $unit_config --socket $unit_socket_arg daemon
WorkingDirectory=$unit_home
Environment=PYTHONUNBUFFERED=1
Restart=on-failure
RestartSec=1
TimeoutStartSec=120
TimeoutStopSec=10
KillMode=mixed
NoNewPrivileges=yes
UMask=0077
OOMScoreAdjust=100

[Install]
# Socket-activated on purpose: enable dusky_kokoro.socket, not this unit.
EOF
    systemctl --user daemon-reload
    systemctl --user stop dusky_kokoro.service dusky-kokoro.service >/dev/null 2>&1 || true
    systemctl --user reset-failed dusky_kokoro.service dusky-kokoro.service >/dev/null 2>&1 || true
    systemctl --user stop dusky_kokoro.socket dusky-kokoro.socket >/dev/null 2>&1 || true
    systemctl --user disable dusky-kokoro.socket >/dev/null 2>&1 || true
    rm -f "$UNIT_DIR/dusky-kokoro.socket" "$UNIT_DIR/dusky-kokoro.service"
    systemctl --user enable --now dusky_kokoro.socket
    ok "systemd: dusky_kokoro.socket enabled ($(systemctl --user is-active dusky_kokoro.socket))"
}

install_trigger() {
    if [[ "$SCRIPT_DIR/trigger.sh" -ef "$TRIGGER_DIR/trigger.sh" ]]; then
        chmod 755 "$TRIGGER_DIR/trigger.sh"
        ok "trigger.sh already in place ($TRIGGER_DIR/trigger.sh)"
    else
        install -Dm755 "$SCRIPT_DIR/trigger.sh" "$TRIGGER_DIR/trigger.sh"
        ok "installed $TRIGGER_DIR/trigger.sh"
    fi
    mkdir -p "$HOME/.local/bin" "$CONFIG_DIR"
    printf '%s\n' "$DUSKY_HOME" > "$CONFIG_DIR/install-path"
    if [[ -d "$HOME/.local/bin" ]]; then
        ln -sfn "$TRIGGER_DIR/trigger.sh" "$HOME/.local/bin/dusky-kokoro"
        ok "symlinked ~/.local/bin/dusky-kokoro"
        if [[ -f "$SCRIPT_DIR/tui_kokoro.py" && -f "$HOME/user_scripts/dusky_tui/python/main/main.py" ]]; then
            if [[ ! "$SCRIPT_DIR/tui_kokoro.py" -ef "$TRIGGER_DIR/tui_kokoro.py" ]]; then
                install -Dm755 "$SCRIPT_DIR/tui_kokoro.py" "$TRIGGER_DIR/tui_kokoro.py"
            fi
            ln -sfn "$TRIGGER_DIR/tui_kokoro.py" "$HOME/.local/bin/dusky-kokoro-tui"
            ok "symlinked ~/.local/bin/dusky-kokoro-tui (Python Textual TUI)"
        elif [[ -f "$SCRIPT_DIR/tui/kokoro_tui.sh" ]]; then
            if [[ ! "$SCRIPT_DIR/tui/kokoro_tui.sh" -ef "$TRIGGER_DIR/tui/kokoro_tui.sh" ]]; then
                install -Dm755 "$SCRIPT_DIR/tui/kokoro_tui.sh" "$TRIGGER_DIR/tui/kokoro_tui.sh"
            fi
            ln -sfn "$TRIGGER_DIR/tui/kokoro_tui.sh" "$HOME/.local/bin/dusky-kokoro-tui"
            ok "symlinked ~/.local/bin/dusky-kokoro-tui (Bash fallback)"
        fi
    fi
}

self_test() {
    (( SKIP_SELFTEST )) && { info "skipping self test (--skip-selftest)"; return 0; }
    if (( SKIP_MODELS )); then
        info "self test: running doctor diagnostics (synthesis skipped because --skip-models was requested)"
        DUSKY_HOME="$DUSKY_HOME" "$VENV_PY" "$MAIN_PY" doctor
        return 0
    fi
    info "self test: doctor + offline synthesis benchmark"
    if DUSKY_HOME="$DUSKY_HOME" "$VENV_PY" "$MAIN_PY" doctor --synth; then
        ok "self test passed"
    else
        die "self test failed; inspect the diagnostic above"
    fi
}

summary() {
    printf '\n%sReady%s · %s\n\n' "$C_OK" "$C_END" "$(backend_name)"
    printf '  Read     %q --text "Hello."\n' "$HOME/.local/bin/dusky-kokoro"
    [[ ! -e "$HOME/.local/bin/dusky-kokoro-tui" ]] || printf '  Settings %q\n' "$HOME/.local/bin/dusky-kokoro-tui"
    printf '  Config   %s\n  Log      %s\n' "$CONFIG_FILE" "$INSTALL_LOG"
}

backend_name() {
    case "$HW" in
        nvidia) printf 'NVIDIA CUDA' ;; amd) printf 'AMD MIGraphX' ;;
        intel) printf 'Intel OpenVINO' ;; cpu) printf 'CPU' ;;
    esac
}

# --- main ----------------------------------------------------------------------------------------
info "Dusky Kokoro installer $INSTALLER_VERSION"
preflight
scan_gpus
choose_hw
choose_models
check_hw_prereqs
mkdir -p "$DUSKY_HOME"
INSTALL_LOG="$DUSKY_HOME/install.log"
: > "$INSTALL_LOG"
printf '\n'
info "Backend: $(backend_name)"
run_step "Preparing Python environment" setup_env
run_step "Checking runtime" verify_runtime
run_step "Preparing models" fetch_models
run_step "Writing configuration" write_config
(( NO_SYSTEMD )) || run_step "Enabling on-demand service" write_units
run_step "Installing commands" install_trigger
run_step "Testing installation" self_test
summary
