#!/usr/bin/env python3
"""Dusky Template Generator — native messaging host (Python 3.14+, Linux only).

Owns $XDG_CONFIG_HOME/dusky_sites/<domain>.css. Writes atomically
(tmpfile + os.replace + dir fsync) with compare-and-swap revision checking, and
serialises every operation on a domain behind an advisory flock so two browsers
(or two host processes) cannot lose an update between the CAS check and the
rename.

Protocol: stdio, one JSON object per frame, u32 length prefix, struct "=I"
(NATIVE byte order — do NOT "fix" to "@I"; Firefox writes host-endian lengths).

    {"type":"ping"}                                       -> ok, version, dir, python, pid
    {"type":"read",  "domain":d}                          -> ok, domain, path, exists, css, picks, rev, warnings?
    {"type":"write", "domain":d, "css":s, "base_rev":n?}  -> ok, domain, path, exists, css, picks, rev
    {"type":"splice","domain":d,"region":r,"body":s,
                     "base_rev":n?}                       -> same as write
    {"type":"delete","domain":d, "base_rev":n?}           -> ok, domain, path, existed, exists, css, rev
    stale base_rev                                        -> {"ok":false,"conflict":true, ...current state}

"rev" is a 48-bit BLAKE2b digest of the file bytes (0 when absent) — content
identity, fits a JS Number exactly. Every reply echoes "__id". Template = one
@-moz-document block; regions auto (variables first) + picks (cascade last);
hand edits outside the regions are preserved byte-for-byte; an empty template
deletes the file.
"""

import contextlib
import fcntl
import hashlib
import io
import json
import os
import re
import struct
import sys
import tempfile
from collections.abc import Iterator
from pathlib import Path
from typing import Any, Final

type Reply = dict[str, Any]

VERSION: Final = "4.0.0"
HOST_NAME: Final = "dusky_template_generator"
MAX_IN: Final = 8 * 1024 * 1024          # accept generously ...
MAX_OUT: Final = 1024 * 1024 - 1024      # ... Firefox drops host replies over 1 MiB
DIR_MODE: Final = 0o700
FILE_MODE: Final = 0o600

BEGIN: Final[dict[str, str]] = {
    "auto": "/* >>> dusky:auto - regenerated by Auto-map; put hand edits outside this block */",
    "picks": "/* >>> dusky:picks - managed by the Visual Picker, one rule per line */",
}
END: Final[dict[str, str]] = {
    "auto": "/* <<< dusky:auto */",
    "picks": "/* <<< dusky:picks */",
}

# One anchored, non-greedy span per region; BEGIN and END can never be paired
# across different regions or across a stray pasted marker.
REGION_RE: Final[dict[str, re.Pattern[str]]] = {
    name: re.compile(
        r"^[ \t]*" + re.escape(BEGIN[name]) + r"[ \t]*\n(?P<body>.*?)^[ \t]*"
        + re.escape(END[name]) + r"[ \t]*(?:\n|\Z)",
        re.DOTALL | re.MULTILINE,
    )
    for name in BEGIN
}
BEGIN_COUNT_RE: Final[dict[str, re.Pattern[str]]] = {
    name: re.compile(r"^[ \t]*" + re.escape(BEGIN[name]), re.MULTILINE) for name in BEGIN
}
END_COUNT_RE: Final[dict[str, re.Pattern[str]]] = {
    name: re.compile(r"^[ \t]*" + re.escape(END[name]), re.MULTILINE) for name in END
}

_LABEL: Final = r"[a-z0-9_](?:[a-z0-9_-]*[a-z0-9_])?"
_DOMAIN_RE: Final = re.compile(rf"^{_LABEL}(?:\.{_LABEL})*$")


# ─── configuration ───────────────────────────────────────────────────────────

def config_dir() -> Path:
    """$XDG_CONFIG_HOME/dusky_sites (relative XDG values ignored, per the spec)."""
    base = os.environ.get("XDG_CONFIG_HOME", "")
    if not base or not os.path.isabs(base):
        base = str(Path.home() / ".config")
    return Path(base) / "dusky_sites"


def sanitize_domain(raw: object) -> str:
    """Reduce anything URL-ish to a bare lowercase hostname without a leading www.

    Returns "" unless what remains is a valid hostname: labels of [a-z0-9_-]
    (each ≤63 bytes) joined by single dots, never starting or ending with a dot
    or dash, ≤253 bytes total. Non-ASCII is converted to punycode (UTS-46 via
    the stdlib idna codec) so the file name always matches what the Dusky engine
    and @-moz-document domain() see. Junk is rejected, not repaired, so the
    derived file name cannot escape the templates directory.
    """
    s = str(raw or "").strip().lower()
    if "://" not in s and ("/" in s or "?" in s or "#" in s):
        return ""  # a bare input must already be a hostname
    d = re.sub(r"^[a-z][a-z0-9+.-]*://", "", s)     # scheme
    d = re.split(r"[/?#]", d, maxsplit=1)[0]        # path / query / fragment
    d = d.rsplit("@", 1)[-1]                        # userinfo
    d = re.sub(r":\d+$", "", d)                     # port
    d = d.removeprefix("www.").rstrip(".")          # www., FQDN dot
    if not d or d.startswith("."):
        return ""
    if not d.isascii():
        try:
            d = d.encode("idna").decode("ascii")
        except UnicodeError:
            return ""
    if len(d) > 253 or any(len(part) > 63 for part in d.split(".")):
        return ""
    return d if _DOMAIN_RE.fullmatch(d) is not None else ""


# ─── template text manipulation (pure) ───────────────────────────────────────

def wrap(domain: str, body: str = "") -> str:
    inner = ""
    if body.strip():
        inner = "".join(
            f"    {line}\n" if line.strip() else "\n"
            for line in body.strip("\n").splitlines()
        )
    return f'@-moz-document domain("{domain}") {{\n{inner}}}\n'


def moz_span(doc: str) -> tuple[int, int, int, int] | None:
    """(start, inner_start, inner_end, end) of the first @-moz-document block.

    Brace counting that understands strings and comments. A naive doc.find("{")
    points *inside the user's first rule* when the file was hand-written.
    """
    start = doc.find("@-moz-document")
    if start < 0:
        return None
    open_at = doc.find("{", start)
    if open_at < 0:
        return None
    depth = 0
    i = open_at
    n = len(doc)
    quote = ""
    while i < n:
        c = doc[i]
        if quote:
            if c == "\\":
                i += 2
                continue
            if c == quote:
                quote = ""
        elif c in "\"'":
            quote = c
        elif doc.startswith("/*", i):
            close = doc.find("*/", i + 2)
            i = n if close < 0 else close + 2
            continue
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return start, open_at + 1, i, i + 1
        i += 1
    return None


def is_empty_template(doc: str) -> bool:
    """True only when there is nothing left worth keeping on disk.

    Content *outside* the @-moz-document block counts too: a hand-written header
    comment must not vanish just because both managed regions became empty.
    """
    if not doc.strip():
        return True
    span = moz_span(doc)
    if span is None:
        return False                                   # arbitrary user CSS
    start, inner_start, inner_end, end = span
    outside = (doc[:start] + doc[end:]).strip()
    return not doc[inner_start:inner_end].strip() and not outside


def region_body(doc: str, region: str) -> str:
    """Text strictly between the region's marker lines, or ""."""
    m = REGION_RE[region].search(doc)
    return m.group("body") if m else ""


def marker_warnings(doc: str) -> list[str]:
    return [
        f"{name}: duplicate dusky marker lines in this template — "
        f"remove the extra pair by hand, writes to that region are refused"
        for name in BEGIN
        if len(BEGIN_COUNT_RE[name].findall(doc)) > 1
        or len(END_COUNT_RE[name].findall(doc)) > 1
    ]


def _block(region: str, body: str) -> str:
    body = body.strip("\n")
    if not body.strip():
        return ""
    return f"    {BEGIN[region]}\n{body}\n    {END[region]}\n"


def splice(doc: str, domain: str, region: str, body: str) -> str:
    """Replace, insert, or remove one managed region. Text outside is preserved.

    Region order is normalised: auto goes right after the wrapper's opening
    brace, picks right before its closing brace, so picks always cascades last.
    """
    if (len(BEGIN_COUNT_RE[region].findall(doc)) > 1
            or len(END_COUNT_RE[region].findall(doc)) > 1):
        raise ValueError(
            f"template contains more than one '{region}' region marker; "
            f"remove the duplicate by hand before writing"
        )

    block = _block(region, body)
    if not doc.strip():
        doc = wrap(domain)
    elif "@-moz-document" not in doc:
        doc = wrap(domain, doc)                      # adopt hand-written bare CSS

    if (m := REGION_RE[region].search(doc)) is not None:
        return doc[: m.start()] + block + doc[m.end():]      # replace in place
    if not block:                                    # nothing to remove
        return doc

    span = moz_span(doc)
    if span is None:                                 # unparsable — append, lose nothing
        return doc.rstrip("\n") + "\n" + block

    _, inner_start, inner_end, _ = span
    if region == "auto":                             # variables first
        rest = doc[inner_start:]
        rest = rest[1:] if rest.startswith("\n") else rest
        return doc[:inner_start] + "\n" + block + rest
    return doc[:inner_end].rstrip(" \t\n") + "\n" + block + doc[inner_end:]   # picks last


# ─── file system ─────────────────────────────────────────────────────────────

def content_rev(data: bytes | str) -> int:
    """48-bit content revision; 0 for an absent/empty file."""
    if isinstance(data, str):
        data = data.encode("utf-8")
    if not data:
        return 0
    return int.from_bytes(hashlib.blake2b(data, digest_size=6).digest(), "big") or 1


def read_doc(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (FileNotFoundError, NotADirectoryError, IsADirectoryError):
        return ""
    except UnicodeDecodeError:
        # A binary file under a .css name is not ours to interpret, but it must
        # not be silently replaced either: surface it as unparsable content.
        raise ValueError(f"{path} is not valid UTF-8; refusing to touch it") from None


@contextlib.contextmanager
def domain_lock(root: Path, domain: str) -> Iterator[None]:
    """Advisory exclusive lock for one domain, held across read → CAS → write.

    flock(2) is per open-file-description, so it works across processes (two
    Firefox profiles, Firefox + LibreWolf, the CLI selftest) on every local fs
    Arch ships, including btrfs/ext4/xfs/tmpfs. The file is removed on release
    so the store stays clean; correctness never depends on it alone because the
    revision CAS refuses stale writes even if two holders ever overlap.
    """
    root.mkdir(parents=True, exist_ok=True, mode=DIR_MODE)
    lock = root / f".{domain}.lock"
    fd = os.open(lock, os.O_CREAT | os.O_RDWR | os.O_CLOEXEC, FILE_MODE)
    try:
        fcntl.flock(fd, fcntl.LOCK_EX)
        yield
    finally:
        os.close(fd)                                 # releases the lock
        with contextlib.suppress(OSError):
            lock.unlink()                            # best-effort: leave no litter


def sweep_stale_locks(root: Path) -> None:
    """Remove orphaned `.*.lock` files left by older versions (or crashes).

    Only a file nobody currently holds is removed: each candidate is opened
    and exclusively locked non-blocking first, so a live holder is never
    disturbed.
    """
    if not root.is_dir():
        return
    for lock in root.glob(".*.lock"):
        try:
            fd = os.open(lock, os.O_RDWR | os.O_CLOEXEC)
        except OSError:
            continue
        try:
            fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except OSError:
            os.close(fd)                             # live holder — leave it
            continue
        try:
            with contextlib.suppress(OSError):
                lock.unlink()
        finally:
            os.close(fd)


def write_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True, mode=DIR_MODE)
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp, FILE_MODE)
        os.replace(tmp, path)          # atomic: readers see old or new, never partial
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise
    # POSIX durability for the rename itself.
    with contextlib.suppress(OSError):
        dir_fd = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC)
        try:
            os.fsync(dir_fd)
        finally:
            os.close(dir_fd)


def state_reply(path: Path, domain: str, doc: str) -> Reply:
    reply: Reply = {
        "ok": True, "domain": domain, "path": str(path), "exists": path.is_file(),
        "css": doc, "picks": region_body(doc, "picks"), "rev": content_rev(doc),
    }
    if warn := marker_warnings(doc):
        reply["warnings"] = warn
    return reply


def store(path: Path, domain: str, css: str, current: str) -> Reply:
    if is_empty_template(css):
        existed = path.is_file()
        path.unlink(missing_ok=True)
        return {"ok": True, "domain": domain, "path": str(path), "exists": False,
                "existed": existed, "css": "", "picks": "", "rev": 0}
    if "@-moz-document" not in css:
        css = wrap(domain, css)
    if not css.endswith("\n"):
        css += "\n"
    # Identical bytes: no fsync, no new rev, no change broadcast storm.
    if css != current:
        write_atomic(path, css)
    return state_reply(path, domain, css)


def _base_rev(msg: dict[str, Any]) -> int | None:
    raw = msg.get("base_rev")
    if raw is None:
        return None
    try:
        return int(raw)
    except (TypeError, ValueError):
        return None


def _conflict(path: Path, domain: str, current: str) -> Reply:
    reply = state_reply(path, domain, current)
    reply |= {"ok": False, "conflict": True,
              "error": "the file changed on disk since it was read"}
    return reply


def handle(msg: dict[str, Any], root: Path) -> Reply:
    kind = str(msg.get("type", "")).lower()

    if kind == "ping":
        return {"ok": True, "version": VERSION, "host": HOST_NAME, "dir": str(root),
                "python": sys.version.split()[0], "pid": os.getpid()}

    domain = sanitize_domain(msg.get("domain", ""))
    if not domain:
        return {"ok": False, "error": f"Invalid domain: {msg.get('domain')!r}"}
    path = root / f"{domain}.css"

    with domain_lock(root, domain):
        current = read_doc(path)

        if kind == "read":
            return state_reply(path, domain, current)

        # ── compare-and-swap: refuse to overwrite someone else's change ──────
        base = _base_rev(msg)
        if kind in {"write", "splice", "delete"} and base is not None and base != content_rev(current):
            return _conflict(path, domain, current)

        match kind:
            case "write":
                return store(path, domain, str(msg.get("css", "")), current)
            case "splice":
                region = str(msg.get("region", ""))
                if region not in BEGIN:
                    return {"ok": False, "error": f"Unknown region: {region!r}"}
                new = splice(current, domain, region, str(msg.get("body", "")))
                return store(path, domain, new, current)
            case "delete":
                existed = path.is_file()
                path.unlink(missing_ok=True)
                return {"ok": True, "domain": domain, "path": str(path), "existed": existed,
                        "exists": False, "css": "", "picks": "", "rev": 0}
            case _:
                return {"ok": False, "error": f"Unknown message type: {kind!r}"}


# ─── framing ─────────────────────────────────────────────────────────────────

class Truncated(Exception):
    """A frame ended mid-message — distinct from a clean EOF."""


class BadJSON(Exception):
    """The frame was complete but its payload was not a JSON object."""


def read_exact(stream: io.BufferedReader, count: int) -> bytes | None:
    """Exactly count bytes; None on clean EOF at a frame boundary, else Truncated."""
    buf = bytearray()
    while len(buf) < count:
        chunk = stream.read(count - len(buf))
        if not chunk:
            if not buf:
                return None
            raise Truncated(f"stream ended after {len(buf)} of {count} bytes")
        buf += chunk
    return bytes(buf)


def read_message(stream: io.BufferedReader) -> dict[str, Any] | None:
    head = read_exact(stream, 4)
    if head is None:
        return None                                   # browser closed the pipe
    (length,) = struct.unpack("=I", head)
    if length == 0 or length > MAX_IN:
        raise Truncated(f"bad frame length {length}")  # framing is lost: fatal
    data = read_exact(stream, length)
    if data is None:
        raise Truncated("length header without a payload")
    try:
        msg = json.loads(data.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise BadJSON(str(exc)) from None              # framing intact: recoverable
    if not isinstance(msg, dict):
        raise BadJSON("top-level value is not an object")
    return msg


def send_message(stream: io.BufferedWriter, obj: Reply) -> None:
    data = json.dumps(obj, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    if len(data) > MAX_OUT:
        fallback: Reply = {
            "ok": False, "__id": obj.get("__id"),
            "domain": obj.get("domain", ""), "path": obj.get("path", ""),
            "exists": obj.get("exists", False), "rev": obj.get("rev", 0),
            "error": f"reply of {len(data)} bytes exceeds the 1 MiB native messaging limit",
        }
        data = json.dumps(fallback, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    stream.write(struct.pack("=I", len(data)) + data)
    stream.flush()


def serve() -> int:
    root = config_dir()
    sweep_stale_locks(root)                          # one-time: clear pre-fix litter
    stdin, stdout = sys.stdin.buffer, sys.stdout.buffer
    while True:
        try:
            msg = read_message(stdin)
        except Truncated as exc:                      # framing is lost; never guess
            send_message(stdout, {"ok": False, "error": f"malformed frame: {exc}"})
            return 1
        except BadJSON as exc:                        # one bad frame is survivable
            send_message(stdout, {"ok": False, "error": f"malformed message: {exc}"})
            continue
        if msg is None:
            return 0
        rid = msg.get("__id")
        try:
            reply = handle(msg, root)
        except (OSError, ValueError) as exc:
            reply = {"ok": False, "error": f"{type(exc).__name__}: {exc}"}
        if rid is not None:
            reply["__id"] = rid
        try:
            send_message(stdout, reply)
        except BrokenPipeError:
            return 0


# ─── self test ───────────────────────────────────────────────────────────────

def selftest() -> int:
    """Exercise framing, sanitising, CAS, splicing and atomic storage."""
    import io as _io
    import tempfile as _tempfile

    checks = 0

    def ok(cond: object, what: str) -> None:
        nonlocal checks
        checks += 1
        if not cond:
            raise AssertionError(what)
        print(f"  ok  {what}")

    print("dusky_template_host selftest — python", sys.version.split()[0])

    # framing round-trip, including __id echo
    buf = _io.BytesIO()
    send_message(buf, {"ok": True, "__id": 7, "x": "é"})
    buf.seek(0)
    got = read_message(_io.BufferedReader(_io.BytesIO(buf.getvalue())))
    ok(got == {"ok": True, "__id": 7, "x": "é"}, "frame round-trips with __id echo")

    # domain sanitising
    ok(sanitize_domain("https://www.YouTube.com/watch?v=1") == "youtube.com", "URL → host")
    ok(sanitize_domain("user:pw@Example.COM:8443") == "example.com", "userinfo+port stripped")
    ok(sanitize_domain("münchen.de") == "xn--mnchen-3ya.de", "IDN → punycode")
    ok(sanitize_domain("localhost") == "localhost", "localhost kept")
    ok(sanitize_domain("127.0.0.1") == "127.0.0.1", "ipv4 kept")
    for bad in ("../etc/passwd", ".hidden", "a/b", "a b", "[::1]", "-lead.com", "x." + "y" * 64, ""):
        ok(sanitize_domain(bad) == "", f"rejected {bad!r}")

    # revisions
    ok(content_rev("") == 0, "empty rev is 0")
    ok(content_rev("a") == content_rev("a"), "rev is stable")
    ok(content_rev("a") != content_rev("b"), "rev distinguishes content")
    ok(content_rev("a") < 2 ** 53, "rev fits a JS Number")

    with _tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        dom = "example.com"
        path = root / f"{dom}.css"

        r = handle({"type": "read", "domain": dom}, root)
        ok(r["ok"] and not r["exists"] and r["rev"] == 0, "read of a missing file")

        r = handle({"type": "splice", "domain": dom, "region": "picks",
                    "body": "    a { color: red }"}, root)
        ok(r["ok"] and path.is_file(), "splice creates the file")
        ok('@-moz-document domain("example.com")' in r["css"], "wrapper written")
        ok("a { color: red }" in r["picks"], "picks body echoed without markers")
        rev1 = r["rev"]

        r2 = handle({"type": "splice", "domain": dom, "region": "picks",
                     "body": "    a { color: red }"}, root)
        ok(r2["rev"] == rev1, "idempotent splice keeps the rev (no rewrite)")

        r = handle({"type": "splice", "domain": dom, "region": "auto",
                    "body": "    :root { --x: 1 }"}, root)
        ok(r["css"].index("dusky:auto") < r["css"].index("dusky:picks"), "auto precedes picks")

        stale = handle({"type": "splice", "domain": dom, "region": "picks",
                        "body": "x{}", "base_rev": rev1}, root)
        ok(not stale["ok"] and stale["conflict"], "stale base_rev conflicts")
        ok(stale["rev"] == content_rev(path.read_text()), "conflict carries current state")

        fresh = handle({"type": "splice", "domain": dom, "region": "picks",
                        "body": "    b { color: blue }", "base_rev": stale["rev"]}, root)
        ok(fresh["ok"], "fresh base_rev accepted")

        # hand edits outside the regions survive
        doc = path.read_text()
        path.write_text("/* my header */\n" + doc, encoding="utf-8")
        r = handle({"type": "splice", "domain": dom, "region": "picks",
                    "body": "    c { color: lime }"}, root)
        ok(r["css"].startswith("/* my header */"), "hand edits byte-preserved")

        # removing both regions with content outside keeps the file
        handle({"type": "splice", "domain": dom, "region": "auto", "body": ""}, root)
        r = handle({"type": "splice", "domain": dom, "region": "picks", "body": ""}, root)
        ok(r["exists"], "file with outside content survives empty regions")
        ok("dusky:picks" not in r["css"], "empty body removes its region only")

        # a template that is empty everywhere is deleted
        path.write_text(wrap(dom), encoding="utf-8")
        r = handle({"type": "write", "domain": dom, "css": wrap(dom)}, root)
        ok(not r["exists"] and not path.exists(), "empty template deletes the file")

        # bare hand-written CSS is adopted, not sliced apart
        path.write_text("h1 { color: red }\n", encoding="utf-8")
        r = handle({"type": "splice", "domain": dom, "region": "picks", "body": "    z{}"}, root)
        ok("h1 { color: red }" in r["css"] and r["css"].count("@-moz-document") == 1,
           "bare CSS adopted into one wrapper")

        # duplicate markers warn and refuse
        path.write_text(f"{BEGIN['picks']}\n{END['picks']}\n{BEGIN['picks']}\n{END['picks']}\n",
                        encoding="utf-8")
        r = handle({"type": "read", "domain": dom}, root)
        ok(r.get("warnings"), "duplicate markers warn on read")
        try:
            handle({"type": "splice", "domain": dom, "region": "picks", "body": "q{}"}, root)
            ok(False, "duplicate markers refuse the write")
        except ValueError:
            # handle() raises; serve() converts it to an error reply at runtime.
            ok(True, "duplicate markers refuse the write")

        # file mode and directory mode
        handle({"type": "write", "domain": dom, "css": "p{color:red}"}, root)
        ok(path.stat().st_mode & 0o777 == FILE_MODE, "template is 0600")

        r = handle({"type": "delete", "domain": dom}, root)
        ok(r["ok"] and r["existed"] and not path.exists(), "delete removes the file")
        ok(not handle({"type": "read", "domain": "  "}, root)["ok"], "invalid domain refused")
        ok(not handle({"type": "nope", "domain": dom}, root)["ok"], "unknown type refused")
        ok(handle({"type": "ping"}, root)["version"] == VERSION, "ping reports the version")

    print(f"\nall {checks} checks passed — host is healthy")
    return 0


if __name__ == "__main__":
    raise SystemExit(selftest() if "--selftest" in sys.argv[1:] else serve())