#!/usr/bin/env python3
"""
Dusky Template Generator - native messaging host.

One job: own the per-site template files

    $XDG_CONFIG_HOME/dusky_sites/<domain>.css      (default ~/.config/dusky_sites/)

on behalf of the WebExtension. Nothing else. The separate Dusky Sites engine
reads these files; this host only writes them, atomically.

Protocol: WebExtensions native messaging over stdio. Every message is one JSON
object, UTF-8, prefixed by an unsigned 32-bit length in *native* byte order
("=I" - that is what the spec says; on x86-64/aarch64 it is little-endian).

    {"type": "ping"}                                           -> {"ok": true, "version", "dir", "python"}
    {"type": "read",   "domain": d}                            -> {"ok": true, "domain", "path", "exists", "css", "picks"}
    {"type": "write",  "domain": d, "css": s}                  -> {"ok": true, "domain", "path", "exists", "css"}
    {"type": "splice", "domain": d, "region": r, "body": s}   (r = "auto" | "picks")  -> same as write
    {"type": "delete", "domain": d}                            -> {"ok": true, "domain", "path", "existed"}
    anything else / any failure                                -> {"ok": false, "error": "..."}

A template is one @-moz-document block. Two optional marker regions inside it
are machine-managed; everything outside them is the user's and is preserved:

    /* >>> dusky:auto ... */   Auto-map output, regenerated on every run
    /* >>> dusky:picks ... */  Visual Picker rules, one rule per line

An empty template is deleted rather than written; bare rules without a
@-moz-document wrapper are wrapped so the engine always gets scoped CSS.

    python3 dusky_template_host.py --selftest      offline check of framing + file logic
"""

from __future__ import annotations

import io
import json
import os
import re
import struct
import sys
import tempfile
from pathlib import Path

VERSION = "2.0.0"
HOST_NAME = "dusky_template_generator"
MAX_IN = 8 * 1024 * 1024            # be generous with what we accept ...
MAX_OUT = 1024 * 1024 - 512         # ... but Firefox drops host replies above 1 MiB

BEGIN = {
    "auto": "/* >>> dusky:auto - regenerated by Auto-map; put hand edits outside this block */",
    "picks": "/* >>> dusky:picks - managed by the Visual Picker, one rule per line */",
}
END = {
    "auto": "/* <<< dusky:auto */",
    "picks": "/* <<< dusky:picks */",
}

_LABEL = r"[a-z0-9_](?:[a-z0-9_-]*[a-z0-9_])?"
_DOMAIN_RE = re.compile(rf"^{_LABEL}(?:\.{_LABEL})*$")


# ─── configuration ───────────────────────────────────────────────────────────

def config_dir() -> Path:
    """$XDG_CONFIG_HOME/dusky_sites, falling back to ~/.config (relative XDG values are ignored, per spec)."""
    base = os.environ.get("XDG_CONFIG_HOME", "")
    if not base or not os.path.isabs(base):
        base = str(Path.home() / ".config")
    return Path(base) / "dusky_sites"


def sanitize_domain(raw: object) -> str:
    """Reduce anything URL-ish to a bare lowercase hostname without a leading www.

    Returns "" unless what is left is a valid hostname: labels of [a-z0-9_-] joined
    by single dots, never starting or ending with a dot or dash. Junk is rejected,
    not "repaired", so the file name built from the result cannot escape the
    templates directory (no '/', no '..', no leading '.').
    """
    d = str(raw or "").strip().lower()
    d = re.sub(r"^[a-z][a-z0-9+.-]*://", "", d)         # scheme
    d = re.split(r"[/?#]", d, maxsplit=1)[0]            # path / query / fragment
    d = d.rsplit("@", 1)[-1]                             # userinfo
    d = re.sub(r":\d+$", "", d)                          # port
    d = d.removeprefix("www.").rstrip(".")               # www. prefix, FQDN trailing dot
    return d if len(d) <= 253 and _DOMAIN_RE.fullmatch(d) is not None else ""


# ─── template text manipulation (pure functions) ─────────────────────────────

def wrap(domain: str, body: str = "") -> str:
    inner = "".join("    " + line + "\n" for line in body.strip("\n").splitlines()) if body.strip() else ""
    return f'@-moz-document domain("{domain}") {{\n{inner}}}\n'


def is_empty_template(doc: str) -> bool:
    a, b = doc.find("{"), doc.rfind("}")
    inner = doc[a + 1:b] if 0 <= a < b else doc
    return not inner.strip()


def region_body(doc: str, region: str) -> str:
    """Text between the region's marker lines, or ""."""
    i = doc.find(BEGIN[region])
    j = doc.find(END[region], i + 1) if i >= 0 else -1
    if i < 0 or j < 0:
        return ""
    start = doc.find("\n", i) + 1
    stop = doc.rfind("\n", 0, j) + 1
    return doc[start:stop] if start <= stop else ""


def splice(doc: str, domain: str, region: str, body: str) -> str:
    """Replace (or insert, or remove when body is blank) one managed region.

    The auto region is inserted right after the opening brace, picks right before
    the closing brace. Text outside the region is returned byte-for-byte.
    """
    begin, end = BEGIN[region], END[region]
    body = body.strip("\n")
    block = f"    {begin}\n{body}\n    {end}\n" if body.strip() else ""
    if not doc.strip():
        doc = wrap(domain)
    i = doc.find(begin)
    j = doc.find(end, i + 1) if i >= 0 else -1
    if i >= 0 and j >= 0:                                        # replace in place
        start = doc.rfind("\n", 0, i) + 1
        nl = doc.find("\n", j)
        stop = len(doc) if nl < 0 else nl + 1
        return doc[:start] + block + doc[stop:]
    if not block:
        return doc
    if region == "auto":                                         # variables first
        k = doc.find("{")
        if k >= 0:
            at = k + 1
            rest = doc[at:]
            rest = rest[1:] if rest.startswith("\n") else rest
            return doc[:at] + "\n" + block + rest
    k = doc.rstrip().rfind("}")                                  # picks last
    if k < 0:
        return doc.rstrip("\n") + "\n" + block
    return doc[:k].rstrip(" \t\n") + "\n" + block + doc[k:]


# ─── file system ─────────────────────────────────────────────────────────────

def write_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)                                    # atomic: readers see old or new, never partial
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise

    # Directory fsync for POSIX durability
    try:
        dir_fd = os.open(str(path.parent), os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(dir_fd)
        finally:
            os.close(dir_fd)
    except OSError:
        pass


def store(path: Path, domain: str, css: str) -> dict:
    if is_empty_template(css):
        path.unlink(missing_ok=True)
        return {"ok": True, "domain": domain, "path": str(path), "exists": False, "css": ""}
    if "@-moz-document" not in css:
        css = wrap(domain, css)
    if not css.endswith("\n"):
        css += "\n"
    write_atomic(path, css)
    return {"ok": True, "domain": domain, "path": str(path), "exists": True, "css": css}


def handle(msg: dict, root: Path) -> dict:
    kind = str(msg.get("type", "")).lower()
    if kind == "ping":
        return {"ok": True, "version": VERSION, "dir": str(root), "python": sys.version.split()[0]}
    domain = sanitize_domain(msg.get("domain", ""))
    if not domain:
        return {"ok": False, "error": f"Invalid domain: {msg.get('domain')!r}"}
    path = root / f"{domain}.css"
    if kind == "read":
        css = path.read_text(encoding="utf-8") if path.is_file() else ""
        return {"ok": True, "domain": domain, "path": str(path), "exists": bool(css),
                "css": css, "picks": region_body(css, "picks")}
    if kind == "write":
        return store(path, domain, str(msg.get("css", "")))
    if kind == "splice":
        region = str(msg.get("region", ""))
        if region not in BEGIN:
            return {"ok": False, "error": f"Unknown region: {region!r}"}
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        return store(path, domain, splice(current, domain, region, str(msg.get("body", ""))))
    if kind == "delete":
        existed = path.is_file()
        path.unlink(missing_ok=True)
        return {"ok": True, "domain": domain, "path": str(path), "existed": existed}
    return {"ok": False, "error": f"Unknown message type: {kind!r}"}


# ─── framing ─────────────────────────────────────────────────────────────────

def read_exact(stream, count: int) -> bytes | None:
    """Read exactly count bytes from stream. Returns None on clean EOF."""
    buf = bytearray()
    while len(buf) < count:
        chunk = stream.read(count - len(buf))
        if not chunk:
            return None if len(buf) == 0 else bytes(buf)
        buf += chunk
    return bytes(buf)


def read_message(stream) -> dict | None:
    head = read_exact(stream, 4)
    if head is None or len(head) < 4:
        return None                                              # clean EOF: browser closed the pipe
    (length,) = struct.unpack("=I", head)
    if length == 0 or length > MAX_IN:
        raise ValueError(f"bad frame length {length}")
    data = read_exact(stream, length)
    if data is None or len(data) < length:
        return None
    msg = json.loads(data.decode("utf-8"))
    return msg if isinstance(msg, dict) else {}


def send_message(stream, obj: dict) -> None:
    data = json.dumps(obj, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    if len(data) > MAX_OUT:
        data = json.dumps({"ok": False, "error": f"reply of {len(data)} bytes exceeds the 1 MiB limit"}).encode()
    stream.write(struct.pack("=I", len(data)) + data)
    stream.flush()


def serve() -> int:
    root = config_dir()
    stdin, stdout = sys.stdin.buffer, sys.stdout.buffer
    while True:
        try:
            msg = read_message(stdin)
        except ValueError as exc:                                # json.JSONDecodeError is a ValueError
            send_message(stdout, {"ok": False, "error": f"malformed message: {exc}"})
            return 1                                             # framing is lost; do not guess
        if msg is None:
            return 0
        try:
            reply = handle(msg, root)
        except (OSError, ValueError) as exc:
            reply = {"ok": False, "error": f"{type(exc).__name__}: {exc}"}
        try:
            send_message(stdout, reply)
        except BrokenPipeError:
            return 0


# ─── self test (python3 dusky_template_host.py --selftest) ───────────────────

def selftest() -> int:
    def expect(cond: bool, what: str) -> None:
        if not cond:
            raise SystemExit(f"selftest FAILED: {what}")

    buf = io.BytesIO()
    send_message(buf, {"type": "ping"})
    buf.seek(0)
    expect(read_message(buf) == {"type": "ping"}, "framing round-trip")
    expect(sanitize_domain("https://user@www.GitHub.com:443/a/b?c#d") == "github.com", "url -> domain")
    expect(sanitize_domain("xn--mnchen-3ya.de") == "xn--mnchen-3ya.de", "punycode kept")
    expect(sanitize_domain("127.0.0.1") == "127.0.0.1" and sanitize_domain("localhost") == "localhost", "ip / localhost")
    for bad in ("", "..", ".hidden", "../../etc/passwd", "a..b", "-x", "bad domain!", "[::1]"):
        expect(sanitize_domain(bad) == "", f"rejects {bad!r}")
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        pick = "    a.x { color: red !important; } /* text: primary */"
        r = handle({"type": "splice", "domain": "example.com", "region": "picks", "body": pick}, root)
        expect(r["ok"] and r["exists"] and r["css"].startswith('@-moz-document domain("example.com")'), "first splice creates file")
        expect(handle({"type": "splice", "domain": "example.com", "region": "picks", "body": pick}, root)["css"] == r["css"], "splice is idempotent")
        auto = "    :root, body {\n        --bg: var(--surface) !important;\n    }"
        r2 = handle({"type": "splice", "domain": "example.com", "region": "auto", "body": auto}, root)
        expect(r2["css"].index("dusky:auto") < r2["css"].index("dusky:picks"), "auto region sits above picks")
        rd = handle({"type": "read", "domain": "example.com"}, root)
        expect(rd["exists"] and pick.strip() in rd["picks"] and "dusky:" not in rd["picks"], "read returns picks body")
        r3 = handle({"type": "splice", "domain": "example.com", "region": "picks", "body": ""}, root)
        expect("dusky:picks" not in r3["css"] and "dusky:auto" in r3["css"], "blank body removes only its region")
        r4 = handle({"type": "splice", "domain": "example.com", "region": "auto", "body": ""}, root)
        expect(not r4["exists"] and not (root / "example.com.css").exists(), "empty template is deleted")
        r5 = handle({"type": "write", "domain": "example.com", "css": "b { x: y }"}, root)
        expect(r5["css"].startswith("@-moz-document") and "    b { x: y }" in r5["css"], "bare rules get wrapped")
        expect(handle({"type": "delete", "domain": "example.com"}, root)["existed"], "delete reports existed")
        expect(not handle({"type": "read", "domain": "../x"}, root)["ok"], "invalid domain is refused")
        expect(not handle({"type": "nope", "domain": "example.com"}, root)["ok"], "unknown type is refused")
    print(f"selftest OK  (host {VERSION}, python {sys.version.split()[0]}, templates -> {config_dir()})")
    return 0


if __name__ == "__main__":
    sys.exit(selftest() if "--selftest" in sys.argv[1:] else serve())
