source = $HOME/.config/matugen/generated/hyprlock-colors.conf

$clock_font = Google Sans Flex Freeze
$ui_font = Google Sans Flex Freeze

general {
    grade = 1
    fractional_scaling = 2
    immediate_render = false
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    bezier = accel, 0.2, 0.0, 0.1, 1.0
    animation = fadeIn, 1, 5, accel
    animation = fadeOut, 1, 5, accel
    animation = inputFieldDots, 1, 2, accel
}

# Same wallpaper as SDDM + 40% dim like SDDM idle
background {
    monitor =
    path = $HOME/.cache/current_wallpaper
    blur_size = 6
    blur_passes = 2
    noise = 0.0117
    contrast = 1.30
    brightness = 0.6
    vibrancy = 0.21
    vibrancy_darkness = 0.0
}

# Hours - dynamic vivid (a bit thicker)
label {
    monitor =
    text = cmd[update:1000] echo "<span weight='600'>$(date +'%H')</span>"
    color = $text_color
    font_size = 150
    font_family = $clock_font
    position = 0, 185
    halign = center
    valign = center
}

# Minutes - dynamic pastel (a bit thicker)
label {
    monitor =
    text = cmd[update:1000] echo "<span weight='600'>$(date +'%M')</span>"
    color = $entry_color
    font_size = 150
    font_family = $clock_font
    position = 0, 25
    halign = center
    valign = center
}

# Weekday stacked like stacked_clock
label {
    monitor =
    text = cmd[update:18000000] echo "$(date +'%A')"
    color = $text_color
    font_size = 18
    font_family = JetBrainsMono NFM Bold
    position = 0, -85
    halign = center
    valign = center
}

# Month + day stacked
label {
    monitor =
    text = cmd[update:18000000] echo "$(date +'%d %b')"
    color = $text_color
    font_size = 14
    font_family = JetBrainsMono NFM Bold
    position = 0, -110
    halign = center
    valign = center
}

# --- Username pill ---
shape {
    monitor =
    size = 200, 36
    color = $entry_background_color
    rounding = 18
    border_size = 0
    position = 0, 210
    halign = center
    valign = bottom
    zindex = 0
}

label {
    monitor =
    text = $USER
    color = $text_color
    font_size = 14
    font_family = JetBrainsMono NFM Bold
    position = 0, 215
    halign = center
    valign = bottom
    zindex = 1
}

# --- Password box ---
input-field {
    monitor =
    size = 260, 48
    outline_thickness = 2
    inner_color = $entry_background_color
    outer_color = $entry_border_color
    check_color = rgba(a569dfff) rgba(5dade2ee) 120deg
    fail_color = rgba(c0392bee) rgba(8e44adee) 40deg
    font_color = $entry_color
    font_family = $ui_font
    placeholder_text = Enter password...
    fail_text = $PAMFAIL
    rounding = 22
    dots_size = 0.26
    dots_spacing = 0.64
    dots_center = true
    dots_rouding = -1
    fade_on_empty = true
    position = 0, 135
    halign = center
    valign = bottom
}
