# ==============================================================================
# Terraria Profile
# ==============================================================================

extends = "base_native"

[meta]
id = "terraria"
name = "Terraria"
version = "1.4.5.6"
icon = "applications-games"
developer = "Re-Logic"
genre = "Sandbox / Adventure"
description = "Dig, fight, explore, build: the world is at your fingertips as you fight for survival, fortune, and glory."

[paths]
game_dir = "/mnt/media/games/good_quality/Terraria-jc141"
executable = "Terraria.bin.x86_64"
arguments = []

[runtime]
type = "native"

[graphics]
gpu = "integrated"
wayland_native = true

[graphics.gamescope]
enabled = false

[performance]
gamemode = true
mangohud = false
fps_limit = 60
