extends = "base_wine_dxvk"

[meta]
id = "witch_hunt"
name = "Witch Hunt"
version = "1.0"
icon = "applications-games"
developer = "Unknown"
genre = "Horror / Adventure"
description = "First-person folk horror - hunt witches through cursed villages and dark forests armed with period weapons and folklore."

[paths]
game_dir = "/mnt/media/games/unknown_quality/Witch.Hunt-jc141"
dwarfs_image = "files/game-root.dwarfs"
dwarfs_mount = "files/.game-root-mnt"
overlay_dir = "files/game-root"
overlay_storage = "files/overlay-storage"
overlay_work = "files/.game-root-work"
executable = "Witch_Hunt.exe"
arguments = []

[runtime]
type = "wine"

[runtime.wine]
prefix_dir = "files/wine-prefix-ew"
arch = "win64"
sync_mode = "fsync"
dxvk = true
vkd3d = true

[runtime.wine.dll_overrides]
"winemenubuilder.exe" = "d"
mshtml = "d"
dxgi = "n,b"
d3d11 = "n,b"
d3d12 = "n,b"
d3d9 = "n,b"

[graphics]
gpu = "auto"
wayland_native = true

[graphics.gamescope]
enabled = false

[performance]
gamemode = true
mangohud = false
fps_limit = 60
