#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#d: Set up GNOME Keyring for the greetd login screen

from __future__ import annotations

import sys
import os
import subprocess
import importlib

PY_DEPS: dict[str, str] = {
    "rich": "python-rich",
    "tomlkit": "python-tomlkit",
    "psutil": "python-psutil",
}

def _bootstrap() -> None:
    missing: list[str] = []
    for mod, pkg in PY_DEPS.items():
        try:
            importlib.import_module(mod)
        except ImportError:
            missing.append(pkg)
    if not missing:
        return
    if os.geteuid() != 0:
        print("[bootstrap] Root required to install missing Python dependencies. Escalating via sudo...")
        try:
            os.execvp("sudo", ["sudo", "-p", "[sudo] password for %u: ", sys.executable] + sys.argv)
        except FileNotFoundError:
            print("[bootstrap] ERROR: sudo not found. Please run as root.")
            sys.exit(1)
    print(f"[bootstrap] Installing missing Python deps via pacman: {' '.join(missing)}")
    try:
        subprocess.check_call(["pacman", "-S", "--needed", "--noconfirm"] + missing)
    except subprocess.CalledProcessError as e:
        print(f"[bootstrap] ERROR: pacman failed to install {missing}. Exit code {e.returncode}")
        print("Please install manually: sudo pacman -S " + " ".join(missing))
        print("Arch policy: never use pip --break-system-packages as root.")
        sys.exit(1)
    # Re-exec to load newly installed modules
    os.execv(sys.executable, [sys.executable] + sys.argv)

_bootstrap()

import argparse
import json
import re
import shutil
import tempfile
import time
import signal
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final
import pwd

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.tree import Tree
from rich.syntax import Syntax
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn, TimeElapsedColumn
from rich.prompt import Confirm
from rich.rule import Rule
from rich import box
from rich.traceback import install as rich_traceback_install

import tomlkit  # type: ignore
import psutil  # type: ignore

rich_traceback_install(show_locals=False)
console = Console()

VERSION: Final = "4.1.0-final-fixed"
SYSTEM_PKGS: Final[list[str]] = [
    "greetd",
    "greetd-tuigreet",
    "udiskie",
    "libsecret",
    "gnome-keyring",
    "hyprland",
    "hyprland-guiutils",
]

WAYLAND_SESSION: Final[Path] = Path("/usr/local/bin/wayland-session")
GREETD_CFG: Final[Path] = Path("/etc/greetd/config.toml")
PAM_GREETD: Final[Path] = Path("/etc/pam.d/greetd")
PAM_LOGIN: Final[Path] = Path("/etc/pam.d/login")
OVERRIDE_CONF: Final[Path] = Path("/etc/systemd/system/greetd.service.d/keyringmode.conf")
TUIGREET_CACHE: Final[Path] = Path("/var/cache/tuigreet")

WAYLAND_SESSION_CONTENT: Final[str] = f"""#!/usr/bin/env bash
# Generated by 127_pam_keyring_greetd.py v{VERSION}
# Pure Hyprland 0.55.4+ native session — no UWSM
# start-hyprland provides crash recovery & safe mode (upstream 0.53+)
set -euo pipefail
exec start-hyprland
"""

def run(cmd: list[str], check: bool = True, capture: bool = True) -> subprocess.CompletedProcess:
    console.log(f"[dim]$ {' '.join(cmd)}[/dim]")
    if capture:
        return subprocess.run(cmd, check=check, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    else:
        return subprocess.run(cmd, check=check)

def pacman_installed(pkg: str) -> bool:
    return subprocess.run(["pacman", "-Qq", pkg], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0

def ensure_root_or_escalate() -> None:
    if os.geteuid() == 0:
        return
    console.print(Panel("Root privileges required — re-launching via sudo (password prompt)", style="yellow", title="Elevation"))
    try:
        os.execvp("sudo", ["sudo", "-p", "[sudo] password for %u: ", sys.executable] + sys.argv)
    except FileNotFoundError:
        console.print("[red]sudo not found. Run as root.[/red]")
        sys.exit(1)

def get_real_user() -> tuple[str, Path]:
    su = os.environ.get("SUDO_USER")
    if su and su != "root":
        try:
            pw = pwd.getpwnam(su)
            return su, Path(pw.pw_dir)
        except KeyError:
            pass
    for pw in pwd.getpwall():
        if 1000 <= pw.pw_uid < 60000 and pw.pw_name not in ("nobody", "greeter"):
            return pw.pw_name, Path(pw.pw_dir)
    console.print("[red]FATAL: no regular user UID 1000-59999[/red]")
    sys.exit(1)

def is_root_encrypted() -> bool:
    try:
        fm = json.loads(subprocess.check_output(["findmnt", "-J", "-o", "SOURCE", "/"], text=True))
        src = fm["filesystems"][0]["source"].split("[")[0]
        ls = json.loads(subprocess.check_output(["lsblk", "-J", "-s", "-o", "TYPE,NAME", src], text=True))
        def walk(devs) -> bool:
            for d in devs:
                if d.get("type") == "crypt":
                    return True
                if "children" in d and walk(d["children"]):
                    return True
            return False
        return walk(ls.get("blockdevices", []))
    except Exception:
        try:
            src = subprocess.check_output(["findmnt", "-n", "-o", "SOURCE", "/"], text=True).strip().split("[")[0]
            out = subprocess.check_output(["lsblk", "-s", "-no", "TYPE", src], text=True)
            return "crypt" in out.split()
        except Exception:
            return False

def backup_with_retention(p: Path, keep: int = 5) -> Path | None:
    if not p.exists():
        return None
    bak = p.with_name(f"{p.name}.bak.{int(time.time())}")
    try:
        shutil.copy2(p, bak)
        olds = sorted(p.parent.glob(f"{p.name}.bak.*"), key=lambda x: x.stat().st_mtime, reverse=True)
        for o in olds[keep:]:
            try: o.unlink()
            except: pass
        return bak
    except Exception as e:
        console.log(f"[dim]backup failed {p}: {e}[/dim]")
        return None

def atomic_write(target: Path, content: str | bytes, mode: int = 0o644, owner: str | None = None) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(target.parent), prefix=f".{target.name}.tmp.")
    try:
        if isinstance(content, bytes):
            with os.fdopen(fd, "wb") as f:
                f.write(content)
                f.flush(); os.fsync(f.fileno())
        else:
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
                f.write(content)
                f.flush(); os.fsync(f.fileno())
        os.chmod(tmp, mode)
        if owner:
            try:
                shutil.chown(tmp, user=owner, group=owner)
            except Exception:
                try:
                    pw = pwd.getpwnam(owner)
                    os.chown(tmp, pw.pw_uid, -1)
                except Exception:
                    pass
        os.replace(tmp, target)
    finally:
        Path(tmp).unlink(missing_ok=True)

@dataclass(slots=True)
class Deployer:
    real_user: str
    home: Path
    mode_arg: str
    dry_run: bool = False
    yes: bool = False
    active_mode: str = field(init=False, default="")

    def resolve_mode(self) -> None:
        console.rule("[bold cyan]Stage 1 — Topology & Mode Resolution")
        enc = is_root_encrypted()
        console.print(f"Root LUKS encrypted: [bold]{enc}[/bold]")
        match self.mode_arg:
            case "auto":
                self.active_mode = "luks" if enc else "unencrypted"
                console.print(f"Auto → [green]{self.active_mode}[/green]")
            case "encrypted":
                self.active_mode = "luks"
            case m if m in ("unencrypted", "luks", "autologin"):
                self.active_mode = m
            case _:
                console.print(f"[red]Invalid mode {self.mode_arg}[/red]"); sys.exit(1)
        if self.active_mode == "luks" and not enc:
            console.print("[red]FATAL: luks requested but / not encrypted[/red]")
            sys.exit(1)
        console.print(f"Active: [magenta]{self.active_mode.upper()}[/magenta]")

    def install_system_deps(self) -> None:
        console.rule("[bold cyan]Stage 2 — System Dependencies (pacman, no AUR)")
        missing = [p for p in SYSTEM_PKGS if not pacman_installed(p)]
        if not missing:
            console.print("[green]All system packages installed[/green]")
            if not shutil.which("start-hyprland"):
                console.print("[yellow]start-hyprland missing — reinstalling hyprland[/yellow]")
                missing = ["hyprland", "hyprland-guiutils"]
            else:
                return
        console.print(f"Install: [yellow]{', '.join(missing)}[/yellow]")
        if self.dry_run:
            console.print("[dim]dry-run: would run pacman[/dim]"); return
        with Progress(SpinnerColumn(), TextColumn("{task.description}"), BarColumn(), TaskProgressColumn(), TimeElapsedColumn(), console=console) as prog:
            t = prog.add_task(f"pacman -S {len(missing)}", total=len(missing))
            try:
                res = run(["pacman", "-S", "--needed", "--noconfirm"] + missing, check=True)
                prog.update(t, completed=len(missing))
                console.log(res.stdout[-800:])
            except subprocess.CalledProcessError as e:
                console.print(Panel(f"pacman failed\n{e.stdout}", style="red"))
                sys.exit(1)

    def deploy_wayland_session(self) -> None:
        console.rule("[bold cyan]Stage 3 — /usr/local/bin/wayland-session")
        if self.dry_run:
            console.print(Syntax(WAYLAND_SESSION_CONTENT, "bash", theme="monokai", line_numbers=True)); return
        backup_with_retention(WAYLAND_SESSION)
        atomic_write(WAYLAND_SESSION, WAYLAND_SESSION_CONTENT, mode=0o755)
        assert WAYLAND_SESSION.stat().st_mode & 0o111
        console.print(f"[green]✔[/green] {WAYLAND_SESSION} → exec start-hyprland (0755)")
        console.print(Syntax(WAYLAND_SESSION_CONTENT, "bash", theme="monokai"))

    def setup_tuigreet_cache(self) -> None:
        console.rule("[bold cyan]Stage 4a — /var/cache/tuigreet")
        if self.dry_run:
            console.print(f"would mkdir {TUIGREET_CACHE} 0755 greeter:greeter"); return
        TUIGREET_CACHE.mkdir(parents=True, exist_ok=True)
        os.chmod(TUIGREET_CACHE, 0o755)
        try:
            shutil.chown(TUIGREET_CACHE, user="greeter", group="greeter")
            console.print(f"[green]✔[/green] {TUIGREET_CACHE} greeter:greeter 0755")
        except Exception:
            console.print("[yellow]greeter user not yet present, will fix on next run[/yellow]")

    def write_greetd_config(self) -> None:
        console.rule(f"[bold cyan]Stage 4b — {GREETD_CFG} [{self.active_mode}]")
        doc = tomlkit.document()
        doc.add(tomlkit.comment(f"Generated by {VERSION} — pure Hyprland 0.55.4+"))
        doc.add(tomlkit.comment(f"Mode {self.active_mode} User {self.real_user}"))
        term = tomlkit.table(); term["vt"] = 1
        doc["terminal"] = term
        default = tomlkit.table()
        default["command"] = "tuigreet --time --remember --remember-session --cmd /usr/local/bin/wayland-session"
        default["user"] = "greeter"
        doc["default_session"] = default
        if self.active_mode != "unencrypted":
            init = tomlkit.table()
            init["command"] = "/usr/local/bin/wayland-session"
            init["user"] = self.real_user
            doc["initial_session"] = init
            console.print("[yellow]Autologin via [initial_session][/yellow]")
        else:
            console.print("[green]Standard prompt via [default_session][/green]")
        rendered = tomlkit.dumps(doc)
        if self.dry_run:
            console.print(Syntax(rendered, "toml", theme="monokai", line_numbers=True)); return
        backup_with_retention(GREETD_CFG)
        atomic_write(GREETD_CFG, rendered, mode=0o644)
        try:
            shutil.chown(GREETD_CFG.parent, user="greeter", group="greeter")
            shutil.chown(GREETD_CFG, user="greeter", group="greeter")
        except Exception:
            pass
        console.print(f"[green]✔[/green] {GREETD_CFG}")
        console.print(Syntax(rendered, "toml", theme="monokai", line_numbers=True))

    def _ensure_pam_file(self, path: Path, luks_mode: bool = False) -> bool:
        if not path.exists():
            atomic_write(path, "#%PAM-1.0\n", mode=0o644)
        text = path.read_text(encoding="utf-8", errors="ignore")
        has_auth_gkr = bool(re.search(r'^\s*auth\s+.*\bpam_gnome_keyring\.so\b', text, re.M))
        has_sess_gkr = bool(re.search(r'^\s*session\s+.*\bpam_gnome_keyring\.so\b.*\bauto_start\b', text, re.M))
        has_loadkey = bool(re.search(r'^\s*auth\s+.*\bpam_systemd_loadkey\.so\b', text, re.M))

        if has_auth_gkr and has_sess_gkr and (not luks_mode or has_loadkey):
            console.print(f"  [dim]{path} already ok (luks={luks_mode})[/dim]")
            return False

        lines = text.splitlines()
        def insert_after(pat: str, new_line: str) -> None:
            if any(re.search(re.escape(new_line.strip().split()[0]) + r".*" + re.escape(new_line.strip().split()[-1]) , l) for l in lines):
                # crude dup check, skip if line already present elsewhere
                pass
            idx = -1
            for i,l in enumerate(lines):
                if re.match(pat, l):
                    idx=i
            if idx>=0:
                # avoid duplicate insertion if next line already is new_line
                if idx+1 < len(lines) and lines[idx+1].strip() == new_line.strip():
                    return
                lines.insert(idx+1, new_line)
            else:
                lines.append(new_line)

        # LUKS: pam_systemd_loadkey must come BEFORE pam_gnome_keyring in auth stack
        # Official order from man pam_systemd_loadkey(8):
        #   -auth optional pam_systemd_loadkey.so
        #   -auth optional pam_gnome_keyring.so
        #   -session optional pam_gnome_keyring.so auto_start
        if luks_mode and not has_loadkey:
            insert_after(r'^\s*auth\s+', "auth       optional     pam_systemd_loadkey.so")
            # refresh has_loadkey for ordering, now insert gkr after loadkey
            # find loadkey index and insert gkr after it if not present
            if not has_auth_gkr:
                insert_after(r'pam_systemd_loadkey\.so', "auth       optional     pam_gnome_keyring.so")
        else:
            if not has_auth_gkr:
                insert_after(r'^\s*auth\s+', "auth       optional     pam_gnome_keyring.so")

        if not has_sess_gkr:
            insert_after(r'^\s*session\s+', "session    optional     pam_gnome_keyring.so auto_start")

        # Safety: remove deprecated pam_fde_boot_pw if present (AUR package deprecated)
        filtered = []
        for l in lines:
            if "pam_fde_boot_pw.so" in l:
                console.print(f"  [yellow]Removing deprecated {l.strip()} (replaced by pam_systemd_loadkey)[/yellow]")
                continue
            filtered.append(l)
        lines = filtered

        if self.dry_run:
            console.print(Syntax("\n".join(lines), "ini", theme="monokai"))
            return True
        backup_with_retention(path)
        atomic_write(path, "\n".join(lines)+"\n", mode=0o644)
        console.print(f"  [green]✔ patched[/green] {path} (luks={luks_mode})")
        return True

    def setup_pam(self) -> None:
        console.rule("[bold cyan]Stage 5 — PAM (gnome-keyring + systemd 261 loadkey for LUKS)")
        luks = self.active_mode == "luks"
        for p in (PAM_GREETD, PAM_LOGIN):
            self._ensure_pam_file(p, luks_mode=luks)
        if luks:
            console.print("[dim]LUKS mode: auth pam_systemd_loadkey.so → auth pam_gnome_keyring.so → session ... auto_start (systemd 261 native, replaces pam_fde_boot_pw)[/dim]")
        else:
            console.print("[dim]Standard: auth pam_gnome_keyring.so + session auto_start[/dim]")

    def setup_systemd(self) -> None:
        console.rule("[bold cyan]Stage 6 — systemd KeyringMode + masking (required for Hyprland native)")
        if self.dry_run:
            console.print(f"would write {OVERRIDE_CONF} and mask gnome-keyring units"); return
        atomic_write(OVERRIDE_CONF, "[Service]\nKeyringMode=inherit\n", mode=0o644)
        console.print(f"[green]✔[/green] {OVERRIDE_CONF} (allows PAM daemon to access root kernel keyring for cryptsetup)")
        # Task explicitly requires masking to avoid duplicate daemon race.
        # Hyprland native does dbus-update-activation-environment --systemd --all itself.
        run(["systemctl", "--global", "mask", "gnome-keyring-daemon.service", "gnome-keyring-daemon.socket"], check=False)
        for unit in ("gnome-keyring-daemon.service","gnome-keyring-daemon.socket"):
            link = Path(f"/etc/systemd/user/{unit}")
            try:
                link.parent.mkdir(parents=True, exist_ok=True)
                if link.exists() or link.is_symlink(): link.unlink()
                link.symlink_to("/dev/null")
            except Exception as e:
                console.log(f"[dim]mask fallback {unit}: {e}[/dim]")
        console.print("[green]✔[/green] Masked gnome-keyring-daemon.{service,socket} --global (PAM daemon wins)")

    def setup_udiskie(self) -> None:
        console.rule("[bold cyan]Stage 7 — udiskie")
        cfg_dir = self.home / ".config" / "udiskie"
        cfg = cfg_dir / "config.yml"
        yml = """# Generated by 127_pam_keyring_greetd.py
program_options:
  password_prompt: ["secret-tool", "lookup", "uuid", "{id_uuid}"]
  automount: true
  notify: true
  tray: auto
"""
        if self.dry_run:
            console.print(Syntax(yml,"yaml",theme="monokai")); return
        cfg_dir.mkdir(parents=True, exist_ok=True)
        atomic_write(cfg, yml, mode=0o644)
        try:
            shutil.chown(cfg_dir, user=self.real_user, group=self.real_user)
            shutil.chown(cfg, user=self.real_user, group=self.real_user)
        except Exception as e:
            console.print(f"[yellow]chown failed {e}[/yellow]")
        console.print(f"[green]✔[/green] {cfg}")

    def enable_services(self) -> None:
        console.rule("[bold cyan]Stage 8 — Enable greetd.service")
        if self.dry_run:
            console.print("[dim]would enable greetd.service[/dim]"); return
        is_chroot = subprocess.run(["systemd-detect-virt","-q","--chroot"], stdout=subprocess.DEVNULL).returncode==0
        if is_chroot:
            run(["systemctl","enable","greetd.service","--force"], check=False)
        else:
            run(["systemctl","daemon-reload"], check=False)
            run(["systemctl","enable","greetd.service"], check=False)
        console.print("[green]✔[/green] greetd.service enabled")

    def verify(self) -> None:
        console.rule("[bold green]Verification")
        tree = Tree(f"[bold]Platinum v{VERSION} — {self.active_mode.upper()}[/bold]")
        tree.add(f"[green]{WAYLAND_SESSION}[/green] exec start-hyprland")
        tree.add(f"[green]{GREETD_CFG}[/green]")
        tree.add(f"{PAM_GREETD} & {PAM_LOGIN} patched (loadkey={self.active_mode=='luks'})")
        tree.add(f"{OVERRIDE_CONF} KeyringMode=inherit")
        console.print(tree)
        tbl = Table(title="Checks", box=box.ROUNDED)
        tbl.add_column("Component", style="cyan"); tbl.add_column("Status"); tbl.add_column("Notes", style="dim")
        for name,found,note in [
            ("greetd",shutil.which("greetd"),"daemon"),
            ("tuigreet",shutil.which("tuigreet"),"--time --remember"),
            ("start-hyprland",shutil.which("start-hyprland"),"crash recovery wrapper"),
            ("Hyprland",shutil.which("Hyprland"),"0.55.4+"),
            ("gnome-keyring-daemon",shutil.which("gnome-keyring-daemon"),"PAM-started, masked per spec"),
            ("secret-tool",shutil.which("secret-tool"),"libsecret"),
            ("pam_systemd_loadkey.so",Path("/usr/lib/security/pam_systemd_loadkey.so").exists() or Path("/usr/lib64/security/pam_systemd_loadkey.so").exists(),"systemd 261+ provides LUKS→keyring"),
        ]:
            tbl.add_row(name, "[green]found[/green]" if found else "[red]missing[/red]", note)
        tbl.add_row("Mode", self.active_mode.upper(), "unencrypted vs luks/autologin")
        tbl.add_row("UWSM", "removed", "pure Hyprland")
        console.print(tbl)
        try:
            tomlkit.parse(GREETD_CFG.read_text())
            console.print("[green]✔ TOML valid[/green]")
        except Exception as e:
            if not self.dry_run: console.print(f"[red]TOML invalid {e}[/red]")
        if self.active_mode=="autologin":
            console.print(Panel("[yellow]autologin on unencrypted → keyring LOCKED unless blank[/yellow]", style="red"))

def parse_args():
    p=argparse.ArgumentParser(description="Platinum v4.1 — Hyprland native", formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("-m","--mode",default="auto",choices=["auto","unencrypted","luks","autologin","encrypted"])
    p.add_argument("--dry-run",action="store_true")
    p.add_argument("--yes",action="store_true")
    p.add_argument("--verbose",action="store_true")
    return p.parse_args()

def main():
    signal.signal(signal.SIGINT, lambda *_: (console.print("\n[red]Interrupted[/red]"), sys.exit(130)))
    args=parse_args()
    ensure_root_or_escalate()
    real_user,home=get_real_user()
    console.print(Panel(f"Target: {real_user} Home: {home} Python: {sys.version.split()[0]}", title=f"Platinum v{VERSION}", style="magenta", box=box.DOUBLE))
    deployer=Deployer(real_user=real_user, home=home, mode_arg=args.mode, dry_run=args.dry_run, yes=args.yes)
    if not args.yes and not args.dry_run and args.mode in ("autologin","luks","encrypted"):
        if not Confirm.ask(f"[yellow]Enable autologin for {real_user}?[/yellow]", default=True):
            sys.exit(0)
    deployer.resolve_mode()
    deployer.install_system_deps()
    deployer.deploy_wayland_session()
    deployer.setup_tuigreet_cache()
    deployer.write_greetd_config()
    deployer.setup_pam()
    deployer.setup_systemd()
    deployer.setup_udiskie()
    deployer.enable_services()
    deployer.verify()
    console.print(Rule(f"[bold green]Complete [{deployer.active_mode.upper()}] — reboot to test[/bold green]"))

if __name__=="__main__":
    main()
