-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '{{colors.background.default.hex}}',
  base01 = '{{colors.surface_container_lowest.default.hex}}',
  base02 = '{{colors.surface_container_low.default.hex}}',
  -- FIX: outline_variant #51443b fails WCAG 1.98 on dark bg; use outline #9e8e82 (5.86) for visible comments/line numbers
  base03 = '{{colors.outline.default.hex}}',
  base04 = '{{colors.on_surface_variant.default.hex}}',
  base05 = '{{colors.on_surface.default.hex}}',
  -- FIX: inverse_on_surface #382f28 (1.42) and surface_bright #413731 (1.60) are invisible on dark bg; use light on_surface variants
  base06 = '{{colors.on_surface.default.hex}}',
  base07 = '{{colors.on_surface_variant.default.hex}}',

  base08 = '{{colors.error.default.hex}}',
  base09 = '{{colors.tertiary.default.hex}}',
  base0A = '{{colors.secondary.default.hex}}',
  base0B = '{{colors.primary.default.hex}}',
  -- FIX: *_container darks (#6b3b05, #434a22 etc) are ~1.99 contrast and invisible as FG; use on_*_container lights (~14.3) for WCAG AA
  base0C = '{{colors.on_tertiary_container.default.hex}}',
  base0D = '{{colors.on_primary_container.default.hex}}',
  base0E = '{{colors.on_secondary_container.default.hex}}',
  base0F = '{{colors.on_error_container.default.hex}}',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
-- FIX: previous used bg primary_container #6b3b05 + fg background #19120c => contrast 1.99 invisible; use container bg + on_container fg (7.22) for readable selection
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '{{colors.primary_container.default.hex}}',
  fg = '{{colors.on_primary_container.default.hex}}',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '{{colors.on_tertiary_container.default.hex}}',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '{{colors.tertiary.default.hex}}',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '{{colors.secondary.default.hex}}',
})

-- FIX: inverse_primary #88511c contrast 2.86 fails WCAG; use primary #ffb77a (10.86) for visible keywords
vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '{{colors.primary.default.hex}}',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '{{colors.surface_container_lowest.default.hex}}',
  fg = '{{colors.primary.default.hex}}',
})

-- ============================================================================
-- WCAG CONTRAST FIXES: Override highlight groups that mini.base16 maps to
-- previously-failing base0C/0D/0E/0F or base03/06/07 so they meet 4.5:1 minimum
-- ============================================================================
-- Diagnostics: ensure each severity is distinct and contrast-safe
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '{{colors.error.default.hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn',  { fg = '{{colors.secondary.default.hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo',  { fg = '{{colors.tertiary.default.hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticHint',  { fg = '{{colors.primary.default.hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticOk',    { fg = '{{colors.tertiary.default.hex}}' })

-- Underlines for diagnostics (if using underlines)
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', { sp = '{{colors.error.default.hex}}', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn',  { sp = '{{colors.secondary.default.hex}}', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo',  { sp = '{{colors.tertiary.default.hex}}', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint',  { sp = '{{colors.primary.default.hex}}', undercurl = true })

-- Treesitter / LSP semantic tokens that previously used invisible base0C/D/E
vim.api.nvim_set_hl(0, '@type',      { fg = '{{colors.on_tertiary_container.default.hex}}' })
vim.api.nvim_set_hl(0, '@parameter', { fg = '{{colors.primary.default.hex}}' })
vim.api.nvim_set_hl(0, '@property',  { fg = '{{colors.secondary.default.hex}}' })

-- UI: improve low-contrast elements
vim.api.nvim_set_hl(0, 'LineNr',         { fg = '{{colors.outline.default.hex}}', bg = '{{colors.surface_container_lowest.default.hex}}' })
vim.api.nvim_set_hl(0, 'CursorLineNr',   { fg = '{{colors.on_surface.default.hex}}', bg = '{{colors.surface_container_lowest.default.hex}}', bold = true })
vim.api.nvim_set_hl(0, 'Pmenu',          { fg = '{{colors.on_surface.default.hex}}', bg = '{{colors.surface_container_lowest.default.hex}}' })
vim.api.nvim_set_hl(0, 'PmenuSel',       { fg = '{{colors.on_primary_container.default.hex}}', bg = '{{colors.primary_container.default.hex}}', bold = true })
vim.api.nvim_set_hl(0, 'Search',         { fg = '{{colors.on_primary_container.default.hex}}', bg = '{{colors.primary_container.default.hex}}' })
vim.api.nvim_set_hl(0, 'IncSearch',      { fg = '{{colors.on_tertiary_container.default.hex}}', bg = '{{colors.tertiary_container.default.hex}}' })
-- Ensure FloatBorder and Telescope etc remain visible
vim.api.nvim_set_hl(0, 'FloatBorder',    { fg = '{{colors.outline.default.hex}}', bg = '{{colors.surface_container_lowest.default.hex}}' })
vim.api.nvim_set_hl(0, 'NormalFloat',    { fg = '{{colors.on_surface.default.hex}}', bg = '{{colors.surface_container_lowest.default.hex}}' })
